### ISSUE TITLE
Update routing paths

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#1026]
### Update existing paths
Update our paths to the following:
* [x]  `/realm/settings`
* [x]  `/realm/stats`
* [x]  `/realm/keys`
* [x]  `/realm/events`
* [x]  `/users` => `/realm/users`
* [x]  `/apikeys` => `/realm/api-keys`
* [x]  `/mobileapps` => `/realm/mobile-apps`
* [x]  `/home` => `/codes/issue` (and rename controller)
* [x]  `/stats` => `/codes/stats`

### Make moving paths less errorprone
Currently links often hard-code referenced paths, we should use templating to better ref root path / current page path so moving these would only touch one code location.

**Comment by sethvargo** [comment]
Let's brainstorm this out. Sounds like we both have some ideas 😄

**Comment by whaught** [comment]
> Let's brainstorm this out. Sounds like we both have some ideas 😄

I know you love common frameworks, so I trust your ideas if you've got em

**Comment by sethvargo** [comment]
Also add tests for routes

**Comment by whaught** [comment]
> Also add tests for routes

Cover: https://github.com/google/exposure-notifications-verification-server/pull/1047

**Comment by sethvargo** [comment]
@whaught I think we should leave stats at /realm/stats as-is. While all stats are for codes, that might not be the case in the future. If you agree, let's mark this as done?
