### ISSUE TITLE
Stackdriver Metric Volume optimization

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-verification-server#1060]
Hello 👋 
I was wondering if it's configurable (in both key and verification servers) what sort of metrics are to be exported to Stackdriver.

Our biggest cost on GCP is Stackdriver Metric Volume (exceeding even the cost of delivering zipped keys to 1.5m+ mobile users).

When I look in the Metrics Explorer in Stackdriver at the metric `Metric bytes ingested` I can clearly see that the ones with the highest rate of ingestion (around 1 kB/s!!! for each one of them) have absolutely no use to us:

```
custom.googleapis.com/opencensus/grpc.io/client/received_bytes_per_rpc
custom.googleapis.com/opencensus/grpc.io/client/roundtrip_latency
custom.googleapis.com/opencensus/grpc.io/client/sent_bytes_per_rpc
custom.googleapis.com/opencensus/go.sql/client/latency
custom.googleapis.com/opencensus/redis/client/roundtrip_latency
```
etc.

We don't want to completely turn off metric exporting as we use some of the metrics for `key ingestion` in our monitoring systems.

Thanks for the answer!

**Comment by mikehelmick** [comment]
/assign @yegle 
Can you look into this?

**Comment by yegle** [comment]
Hi Marek, thanks for reporting this issue!

These are the metrics we get for free from opencensus etc. These are occasionally useful (e.g. check Stackdriver gRPC client latency to set appropriate timeout value).

There's currently no way to config/disable them, but I'll add the knob now.
