### ISSUE TITLE
Bulk code issuance

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1061]
### TL;DR

Write a command line tool that process a CSV file in the format of

```
phoneNumber,testDate
```

i.e. 

```
+12065555555,2020-11-10
+13155555555
```

### Design

Needs an admin API key, admin API endpoint, and request rate.
The tool should respect 429s and backoff to quota reset points as well.

/kind enhancement

**Comment by whaught** [comment]
/assign

Taking this one. After some discussion, I think folks are okay with attempting to do this not as a CLI tool, but as a javascript one. This will make it easier to ship and maintain, and lowers the bar to easy use. The downside is we won't be able to write back to files and that sort of thing.

**Comment by whaught** [comment]
I'm going to /close this as done. There may be more to add with error handling and additional fields, but I want to hear that user-feedback before doing more
