### ISSUE TITLE
twilio lookup

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1082]
### TL;DR

Investigate using the lookup API: https://www.twilio.com/docs/lookup
See if this would reduce our false positive SMS sends

/kind enhancement

**Comment by sethvargo** [comment]
Lookup costs money to determine line type (mobile vs land vs voip). We can do it, but it'll add $0.005 per SMS. What kinds of false positives are we seeing?

**Comment by sethvargo** [comment]
https://github.com/google/exposure-notifications-verification-server/pull/1087, but we should talk about the pricing diff.

**Comment by mikehelmick** [comment]
This should likely be optional.

The use cases for this is bulk send where you just have a bunch of phone numbers and don't know if they are landlines, mobile, SMS capable...

**Comment by sethvargo** [comment]
See PR for more information.
