### ISSUE TITLE
Verification Code Status

### ISSUE THREAD

**Issue by Ferrumofomega** [google/exposure-notifications-verification-server#109]
### TL;DR

Once an authentication code is issued for a positive test in the verification service, we would like to track the expiration timestamp and if the code was used, so that we can enable more workflows (both automated at not). Right now the database stores these data, but does not expose to the user and or via API.

[This feature was requested by a jurisdiction looking to launch immediately]

### Design

**Proposal**

**Alternatives considered**

**Resources**

- [Link to documentation](TODO)

**Additional information**

**Comment by crwilcox** [comment]
@Ferrumofomega I may not be understanding your request completely. My initial concern would be leaking of unused verification keys and potential abuse vectors.

Can you provide an example of the API call you would need to enable your scenario?

**Comment by mikehelmick** [comment]
Can you share more about the workflows you wish to enable?

We do plan to give access to statistical data related to code use.

**Comment by sherifkozman** [comment]
@mikehelmick along with the Admin API calls available , would it be possible for an a call to be implemented to check if an issued verification code was used or not.
The Data already exisits in the database about the status of the issues code , can that be availed so a third party integration would be able to get a status of an issued code?

**Comment by mikehelmick** [comment]
It would still be good for us to understand the use cases and determine how much of that should be built directly into this server versus enabled through APIs.

**Comment by sherifkozman** [comment]
The current use case and request would give contact tracers the ability to keep track of issues verification codes, if they were used or not and when were they used. This gives more context to CTs to keep track of the codes they issues for postive tested cases.
Exposing it through an API enables integrating this with exisitng systems within the HAs

**Comment by mikehelmick** [comment]
We probably need to assign a tracking GUID for this purpose since codes can be recycled.

**Comment by sherifkozman** [comment]
Thanks @mikehelmick

**Comment by whaught** [comment]
Note switched to UUIDs: https://github.com/google/exposure-notifications-verification-server/pull/217

**Comment by whaught** [comment]
@Ferrumofomega can you add some detail about the scenario users are looking for here? Are we expecting to check on the status of a single code or many?

**Comment by Ferrumofomega** [comment]
Happily. Our user (a US state) would like a way (updated as of late, this
was going to be manual) to programmatically check the status of a single
code.


Samuel Zimmerman
calendly.com/zimmerman-samuel
814-279-7110

**Comment by whaught** [comment]
I've filed https://github.com/google/exposure-notifications-verification-server/issues/232 as a potential followup. That said there are some open questions about if we will hash these keys (which makes listing less useful)

/close
