### ISSUE TITLE
Limiter should only consume quota on success

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#1091]
At the moment we consume abuse-prevention quota right before issuing a code. If issuance fails repeatedly, we could have an inaccurate count of how many codes a user has issued.

We could take quota on success, but if we're concerned about fail-in-the-middle we might want to instead put back one quota on failure?

/assign

**Comment by sethvargo** [comment]
What kind of failure are you seeing? AFAIK, the only failure that can occur is a database-level issue. If you're concerned about SMS failures, that happens _after_ successful code generation; putting quota back would open up an avenue for abuse.

**Comment by whaught** [comment]
Not seeing failures. The failure I am worried about is database-level. Specifically I made the index on UUID unique and allow it to be client-provided. It gives 409 conflict if there's a dupe, but that consumes quota. The other db failures are less likely, but I wanted to track an issue to think about/remember this case.
