### ISSUE TITLE
Migrate load balancer terraform configs to use official module

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#1099]
There's an official terraform module to set up Cloud Load Balancer that might worth migrate to.

https://github.com/terraform-google-modules/terraform-google-lb-http

Example config: https://github.com/ahmetb/terraform-google-lb-http/tree/serverless/examples/cloudrun

**Comment by sethvargo** [comment]
Nah

**Comment by sethvargo** [comment]
I'm gonna suggest we don't do this.

/close
