### ISSUE TITLE
Add a metric on per-user code issue count.

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-verification-server#1100]
We should be able to report how many codes have a given user issued in the system for a given day.

**Comment by sethvargo** [comment]
Are we emitting the user id too? We need to be careful about the privacy preserving nature...

**Comment by yegle** [comment]
Is exposing the numerical user id a concern here? We otherwise won't be able to identify where the excessive verification tokens are issued from.

**Comment by sethvargo** [comment]
It's the numerical ID + timestamp that could be used to correlate back to a real human given enough information.

**Comment by mikehelmick** [comment]
I don't think we want this in the metrics
this is specific to the realm and should stay there

**Comment by mariliamelo** [comment]
As Mike mentioned, a real admin can already see how many codes a given user has issued, so we don't need to export it in the metrics.
