### ISSUE TITLE
Upgrade to Postgres 13

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1103]
https://cloud.google.com/blog/products/databases/cloud-sql-database-service-adds-postgresql-13

**Comment by mikehelmick** [comment]
I am interested in pgaudit and point in time recovery

/kind enhancement

**Comment by sethvargo** [comment]
Proposed migration path for minimal downtime:

1. Tell Terraform to stop managing the existing database resources. This does not delete them, it just removes them from Terraform's understanding of the world:

    ```
    terraform state rm module.en.google_sql_database_instance.db-inst
    terraform state rm module.en.google_sql_database.db
    ```

1. Run a **targeted apply** to create the new databases:

    ```
    tf apply \
      -target module.en.google_sql_database_instance.db-inst \
      -target module.en.google_sql_database.db
    ```

1. Create an export for the old database (it's still active), saving it to Cloud Storage (Web UI is easiest).

1. Restore the backup into the new database.

1. Run a **full apply** to update the Cloud Run services and secrets for the new database. All data is read and written to the new instance.

1. Take another backup of the old database - this is to handle a case where data was written to the old database instance between the original backup and the cut-over.

1. Manually diff and reconcile the first export with the new export.

1. Delete old instance manually (Web UI is easiest).

**Alternative approach**

Instead of doing the reconciliation, we put the old database in read-only mode. There's no "native" way to do this, so we'd have to run actual SQL:

```text
REVOKE INSERT, UPDATE, DELETE FROM verification;
```

Then there'd be no reconciliation, but we'd have downtime.

**Comment by mikehelmick** [comment]
LGTM- should update to reflect that we introduced application level read only mode

**Comment by sethvargo** [comment]
Updated

**Comment by sethvargo** [comment]
This is done in all environments.
