### ISSUE TITLE
Migration 00017 is incorrect

### ISSUE THREAD

**Issue by jeremyfaller** [google/exposure-notifications-verification-server#1158]
Rollback on 00017 is incorrect. It deletes `VerificationCode` twice.

I'm in the middle of something, and can't fix right this second. Marking it here for posterity.

EDITTING:

I'm am less sure this is an issue, but it definitely doesn't remove `UserStats`

**Comment by sethvargo** [comment]
I think many of our rollbacks are incorrect to be honest, and they are really difficult to test.
