### ISSUE TITLE
Require password re-validation or MFA to reset current user's password

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1168]
### TL;DR
The current user needs to provide something at reset time (either MFA or current password).

**Comment by whaught** [comment]
This makes a lot of sense for us to do. Firebase sort-of does this by requiring _recent_ auth. Practically that means that if you haven't logged in in the last two minutes, our password change fails and kicks you out jarringly back to the sign-in page. Requiring reauthenticate right before change will eliminate the mystery failure (and is more secure).
