### ISSUE TITLE
SMS sending of verification codes

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#117]
### TL;DR

Add the ability to send verification codes over SMS

https://www.twilio.com/messaging as likely baked in provider. Must be configurable so operator can bring their own credentials.

/kind enhancement
/priority important-soon

**Comment by mikehelmick** [comment]
One other note - best if the phone numbers don't get stored in the database.

**Comment by sethvargo** [comment]
I have some experience with the Twilio API, so I can take this

**Comment by sherifkozman** [comment]
Twilio has a some considerations to be noted if it is used for an impelemntation that is not in the US.
i.e : Creating a Numeric or Alpha Numeric Sender ID would be a requirement in some destinations and verifying that the server would use those values when posting a payload.
https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID

**Comment by sethvargo** [comment]
I think that's fine. The server operator would need to take those steps, but I don't think it would affect our code. Can you share more about your concerns?

**Comment by sherifkozman** [comment]
I am only noting that the Sender ID (i.e numeric or alpha numeric) is a value that should be factored in when integrating with twilio to ensure portability of the service outside of the US. So it would be set as an ENV variable for example the same way you add Twilio API Key and the application SID. Twilio mostly doesnt handle overriding that value on behalf of the sender.

**Comment by mikehelmick** [comment]
The SMS config will need to be in the database and configured on a per-local basis. See #104

**Comment by mikehelmick** [comment]
Follow up from previous comment

SMS provider and use should be database driven.
If there is no provider configured, then the dialog shouldn't be shown.

As we go multi-tenant, this is important since it is possible that different "realms" will use different SMS config and some might not use SMS at all.

**Comment by sethvargo** [comment]
No no, bad GitHub. That was only part 1 of 1000.
