### ISSUE TITLE
Improve bulk-issue CSV error handling

### ISSUE THREAD

**Issue by kamida** [google/exposure-notifications-verification-server#1197]
### TL;DR

Improve bulk-issue CSV error handling/reporting, so a user can identify and remedy bad CSV rows.

### Design

**Proposal**

- Display table of failed lines (might not scale with very large CSV files)?
- Output error rows to file?
- Generate a summary-report after issue?

**Comment by whaught** [comment]
/close

for now let's see if the error table with line/error message works for users. We can consider generating reports or files if we see the need later.
