### ISSUE TITLE
How to use playbook_test.go

### ISSUE THREAD

**Issue by grpandurangipwc** [google/exposure-notifications-verification-server#1204]
@yegle 

Could you please help with when and how to execute this playbook What is expected from the execution?

https://github.com/google/exposure-notifications-verification-server/blob/main/docs/playbooks/playbook_test.go

**Comment by yegle** [comment]
Hi,

This test is intended to keep the alerts and the playbooks in sync.

You can run it by `go test docs/playbooks/...` if you want, but the test is intended to run before any PR is merged automatically, not by human.
