### ISSUE TITLE
clarify code issue screen

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1212]
### TL;DR

If the SMS is sent - change the text to clarify that the 8 digit code is a backup. Tell the user to check for an SMS, but if they haven't gotten one, they can use this code (But the expiry is short).

![image](https://user-images.githubusercontent.com/92319/100673266-05889180-3318-11eb-8ac4-d467e291404d.png)

Someone other than me should wordsmith this.

This is from reports from a PHA on the system that this screen is confusing to their case workers.

/kind enhancement

**Comment by sethvargo** [comment]
Without SMS:

<img width="709" alt="screenshot-20201130-192331@2x" src="https://user-images.githubusercontent.com/408570/100681382-97f15b00-3341-11eb-89f2-0de492d97120.png">


With SMS:

<img width="708" alt="screenshot-20201130-192345@2x" src="https://user-images.githubusercontent.com/408570/100681372-945dd400-3341-11eb-8fe3-f60ea6b9ebfe.png">
