### ISSUE TITLE
Implement daily active counts

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1222]
### TL;DR

Implement realm level daily active counts via chaff requests.

### Design

**Proposal**

Accept a value for the `X-Chaff` HTTP header.

If a device sends `X-Chaff: daily` it should be counted towards a realm's daily active users. The realm is known since chaff requests require an API key (API key middleware is before chaff handler currently)

Other chaff requests will have `X-Chaff: extra` or just `X-Chaff:` as the header value.

This counts should be on the same refresh schedule as the codes issued / codes consumed.

/kind enhancement

**Comment by sethvargo** [comment]
> API key middleware is before chaff handler currently

Wait, that's not true anymore from https://github.com/google/exposure-notifications-verification-server/pull/1224. I'll flip them around in the PR

**Comment by sethvargo** [comment]
Some design thoughts:

- Move what I did in #1224 to a middleware and accept the database
- Perhaps fail open? It's a chaff request, but I'm not sure we know how clients will/should behave if the request fails due to an internal error

**Comment by mikehelmick** [comment]
agree on the fail open - although we should emit a metric we can alert on if counting of these things is filing.
