### ISSUE TITLE
google_redis_instance has hardcoded zones '-a' & '-c'

### ISSUE THREAD

**Issue by marekaf** [google/exposure-notifications-verification-server#123]
### TL;DR
resource "google_redis_instance" "cache" {
  ...
  location_id             = "${var.region}-a"
  alternative_location_id = "${var.region}-c"
  ...
}

I'm running the infra in europe-west1 which doesn't have `europe-west1-a`

**Expected behavior**
I'd like to be able to either override the redis location and alternative location or use `any`

Alternative solution might be to query Compute Engine API to find out which zones are available for this region

**Observed behavior**
Got 
```
Error creating Instance: googleapi: Error 404: 'europe-west1-a' was not found.
com.google.apps.framework.request.StatusException: <eye3 title='NOT_FOUND'/> generic::NOT_FOUND: 'europe-west1-a' was not found.
```

### Reproduction
```
# terraform.tfvars
region                  = "europe-west1"
cloudscheduler_location = "europe-west1"
appengine_location      = "europe-west"
```

**Comment by sethvargo** [comment]
Should have been auto-closed with GH-124.
