### ISSUE TITLE
Update suggested steps to resolve or what action to take for _ErrorBudgetBurn

### ISSUE THREAD

**Issue by kushal26-pwc** [google/exposure-notifications-verification-server#1255]
Please update alert playbook with possible suggested steps to resolve or action to take when _ErrorBudgetBurn alert gets fired, so that we can recreate these alerts in encv-staging and resolve them.

**Comment by grpandurangipwc** [comment]
We see that documentation on fast/slow error budget burn alert is removed. Will it be created again or the alert itself will be removed?
