### ISSUE TITLE
Correct universal links for iOS 

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#1299]
https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html

Ensure our links conform the to spec format. We have a report that  the json file format of `/.well-known/apple-app-site-association` is incorrect

/assign

**Comment by whaught** [comment]
Note: our implementation conforms to the docs shown here: https://developer.apple.com/documentation/safariservices/supporting_associated_domains
I'm a little skeptical about this archived one - don't want to break existing things.

The report notes existing support of major sites such as:
https://google.com/apple-app-site-association
which follows the former format.

**Comment by mikehelmick** [comment]
Is this resolved now (in 18.2?)

**Comment by whaught** [comment]
Should be
/close
