### ISSUE TITLE
Captcha fails to load on failed login

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1305]
There may be other ways to reproduce but:

1. Attempt to login with a valid email, but invalid password
2. Get login failed error
3. Try to login with the same account with the valid password
4. Get invalid captcha popup:

    <img width="499" alt="screenshot-20201209-150638@2x" src="https://user-images.githubusercontent.com/408570/101681529-411a0e80-3a30-11eb-8331-e76e22b5e559.png">

- Probably should be an alert, maybe a popover
- Probably shouldn't happen 😄 

/assign @whaught

**Comment by whaught** [comment]
Docs for the firebase reset-on-failure is here: https://firebase.google.com/docs/auth/web/phone-auth#use-invisible-recaptcha
