### ISSUE TITLE
Investigate: metric errors

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#1309]
Seeing much of the following in encv logs:

```
Errors during metric descriptor creation: {(metric: custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_used_count, error: The metric already exists.)}.
```

Filing to remember to dig deeper into these

/assign

**Comment by sethvargo** [comment]
@yegle if you have ideas

**Comment by yegle** [comment]
```
"[rpc error: code = AlreadyExists desc = Errors during metric descriptor creation: {(metric: custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_used_count, error: The metric already exists.)}.; rpc error: code = InvalidArgument desc = Field timeSeries[0].points[0].interval.start_time had an invalid value of "2020-12-09T14:35:00.381078-08:00": The start time must be equal to the end time (2020-12-09T18:29:39.177947-08:00) for the gauge metric 'custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_used_count'.]"
```

Looks like `realm_token_used_count` is automatically created as gauge. I think this is another occurrence of  https://github.com/google/exposure-notifications-verification-server/issues/1064

**Comment by yegle** [comment]
The fix I used previously was:

- Go to https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.metricDescriptors/delete
- Delete `projects/encv-prod/metricDescriptors/custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_used_count`

**Comment by yegle** [comment]
The metric was recreated moments later when the next metric exports. The metricKind is correctly created as `CUMULATIVE`.

I think I know the cause of this. A couple days ago I was cleaning up the metrics from encv-prod and deleted a couple of old unused metrics. I might have accidentally deleted this metric and the recreating of the metric is causing it to be created as GAUGE.

```
{
  "name": "projects/encv-prod/metricDescriptors/custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_used_count",
  "labels": [
    {
      "key": "realm"
    },
    {
      "key": "build_id"
    },
    {
      "key": "build_tag"
    }
  ],
  "metricKind": "CUMULATIVE",
  "valueType": "INT64",
  "unit": "1",
  "description": "The count of # of realm token used.",
  "displayName": "OpenCensus/en-verification-server/api/issue/realm_token_used_count",
  "type": "custom.googleapis.com/opencensus/en-verification-server/api/issue/realm_token_used_count",
  "monitoredResourceTypes": [
    ...
  ]
}
