### ISSUE TITLE
SMS template - custom expansions

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#1321]
### TL;DR

Allow for "caseID" expansion in SMS template

A realm should enable this in their realm settings and it should only be shown in issue UI and accepted on the API if enabled.

Use case: a state wants to give a user a caseID# so that if they call back in, they can get in touch w/ case workers easily.

### Design

Add new setting in the UI
add new expansion in the template [caseID]
add to UI and API (and docs) as appropriate.

**Comment by whaught** [comment]
Note, the issue API already gives out a UUID for tracking. We also take in UUID from the client to prevent multiple SMSes on retries. Although this is uuid format, not a generic string, it might be a good stand-in for something like caseID from the users perspective.

**Comment by whaught** [comment]
We had some concerns about identifying pII and caseID - after circling back with the state that asked, this is no longer a requirement.

/close
