### ISSUE TITLE
Custom pin failure errors

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#134]
### TL;DR

Allow PHAs to customizer pin validation failure messages. 
Will allow for providing instructions on how to obtain a new pin.

/kind enhancement

**Comment by mikehelmick** [comment]
Also - for pin error codes, this will be put in place

A pin we don't know about at all is "inavlid"
A pin that was valid, but used is "invalid" (hasn't reached expiry time yet)
A pin that is known and expired is "expired"

**Comment by mikehelmick** [comment]
Also - add in a set of universal error codes so that things can be localized on the client

```
{"Error": "english error message only for devs and logs", "ErrorCode": "code_already_used"}
```

**Comment by mikehelmick** [comment]
Here are the proposed `ErrorCode` strings

- Pin we don't know about would be `"ErrorCode": "code_invalid"`
- Pin that was valid but used would be `"ErrorCode": "code_invalid"`
- Pin that is known and expired would be `"ErrorCode": "code_expired"`

Similar treatment will need to be given to verification token validation.

**Comment by sethvargo** [comment]
I'd recommend keys of `"code"` and `"message"`, but otherwise lgtm

**Comment by mikehelmick** [comment]
/close

this is part of client side config, we now have custom error strings "ErrorCode" in return
