### ISSUE TITLE
Consider deprecating the bulk upload API

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-verification-server#1350]
### TL;DR
We should consider deprecating the bulk upload API and adjust the rate limiting implementation.

### Design

**Proposal**
Deprecate the bulk upload API and improve the rate limiting system.

**Alternatives considered**
Maintain the bulk upload functionality and better document the possible errors and work around failures from other services. 

**Additional information**
The bulk upload feature although useful can be very confusing for one implementing it, since there can be partial success due to dependence on SMS infrastructure.

**Comment by sethvargo** [comment]
Another option is to make the API internal-only (only available on the UI server).

**Comment by whaught** [comment]
I think I noted when creating  this API that it does not conform to Google's standard https://google.aip.dev/233 which does not allow for partial success/failure and requires the entire batch be atomic. Unfortunately that is not possible given that /issue both creates a resource and sends an SMS.

However batch does allow our own bulk-uploader to perform better without messing with throttling or running from multiple IPs. It also allows for server-side parallelization (not implemented) which could create higher overall throughput.

We should definitely throw up some warnings in its documentation if it remains.

**Comment by whaught** [comment]
/close

We have in-the-wild usage of this and have made changes to improve performance and documentation to try to mitigate the onboarding experience. I don't think deprecating is an option (or easy)
