### ISSUE TITLE
Design & implement future key upload

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#137]
On initial report 2 tokens should be sent back

1) the existing verification token
2) a future key upload token that encodes the time period for which future keys may be uploaded

This can be used as the long term token to re-certify and "burn down" the time period for future keys.

This is steps 10-13 of this flow:
https://developers.google.com/android/exposure-notifications/verification-system#flow-diagram

**Comment by sethvargo** [comment]
Going to 

/close

this for now as it's been deprioritized.
