### ISSUE TITLE
Is the length of the verification code configurable or hardcoded ?

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#138]
Is the length of the verification code configurable or hardcoded ? i.e through an env variable

**Comment by lmartensson** [comment]
I just found the answer to this. I see it's configurable by an env variable.

https://github.com/google/exposure-notifications-verification-server/blob/40212b648d729349a76dd2f5aaae70c31df86d10/pkg/config/admin_server_config.go#L25

Would it be possible to do this through the request though? I'm thinking that if we could configure # digits and duration time through an API request, that will be helpful in the cases where we may need more than an hour of validity.

**Comment by mikehelmick** [comment]
@lmartensson is correct, this is configurable through environment variable.

I'm in process of moving this into the database rather than have it be environment variable config.

2 questions, re uses cases:

1) What's the use case for code being dynamic length at runtime?
2) What's the use case for dynamic duration time?

Along what criteria would you decide to change this?

**Comment by lmartensson** [comment]
We're discussing options with HAs for delivering verification codes to users, and if a code is not delivered synchronously over the phone we may need it to be valid for longer than 1 hour. If it's valid for a longer period of time, say, 24h, we'd also like to increase the number of digits to compensate.

**Comment by mikehelmick** [comment]
Thanks - we're currently evaluating multiple code generation functions (i.e. alpha-numeric, greater length).

Going from 1 to 24 hours does require a significantly larger keyspace than the default.

**Comment by zssz** [comment]
@mikehelmick I'm confirming that I've been hearing the same issue raised from the PHAs we're talking to. Going from 1 hour to 24 hour, using just digits, how long should a Verification Code length be, to be safe? 10, 11, 12?

**Comment by mikehelmick** [comment]
I've reached out to some folks inside Google to run those numbers

We're going to build in some additional flexibility around the verification codes to support this use case.

**Comment by lmartensson** [comment]
Thanks Mike!

**Comment by mikehelmick** [comment]
Followup here -

We're going to make a couple of changes around pins

* short term pins will be hardened to 8 digits and be valid for a short period of time. These codes are meant to be read over the phone and human entered
* an additional short term pin of 16 digits will be issued that is valid for 24 hours. This code will only be sent over SMS with the intent of it being deep-linkable into an application.

@lmartensson @zssz @sherifkozman - Any feedback on that plan?

**Comment by mikehelmick** [comment]
Also - we want to store the last 2 digits of the phone number for the history page. (history page still TODO)

**Comment by zssz** [comment]
@mikehelmick, yes, that sounds good! 

On a related note, I'm proposing to shorten the copy of the SMS template to fit into one segment. Currently, it is two. Something similar to:

"Your Exposure Notifications Verification Code is: enapp://3734423687222130"

This message should be able to be configured at the realm-level.

**Comment by mikehelmick** [comment]
Yes - SMS will be configurable at a realm level with some Google provided default.

We'll make sure the default is within one segment, that's a good call out.

**Comment by sherifkozman** [comment]
@mikehelmick one more issue about SMS and length, it would be important to ensure that the message body is always kept as ISO 8859 Latin 1 which is the default for GSM alphabet, any use of unicode or other characters would result to automatically change the max length of an SMS from 160 (english characters) to 70 (unicode) and thus affecting the segment length and cost of message will be doubled.
