### ISSUE TITLE
Integration test: revision scenario

### ISSUE THREAD

**Issue by chaodaiG** [google/exposure-notifications-verification-server#139]
### TL;DR

Add integration test covering the scenario of where the state transitioning from one state to another, as:

1. PHA issued a token says positive/negative
1. Later on, some other test results came back, and PHA issued a token with a different state 

Currently, the only supported scenario is:
```
likely -> {confirmed | negative}
```

**Comment by chaodaiG** [comment]
There's some good stuff in the [publish_test.go](https://github.com/google/exposure-notifications-server/blob/main/internal/publish/publish_test.go) unit test for generating certs etc

**Comment by yegle** [comment]
This should've been covered by the e2e-runner service (h/t to the original e2e-test CLI).
