### ISSUE TITLE
Enable 2FA on firebase auth

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#141]
https://cloud.google.com/identity-platform/docs/web/mfa#enrolling_a_second_factor

/kind enhancement

**Comment by mikehelmick** [comment]
looks like we need to upgrade from firebase auth to cloud identity platform

**Comment by sherifkozman** [comment]
Wouldn't cloud identity requires a GSuite domain attached to it ?

**Comment by mikehelmick** [comment]
I don’t believe so

**Comment by sherifkozman** [comment]
https://support.google.com/cloudidentity/answer/7319251?hl=en

**Comment by mikehelmick** [comment]
haven't completed testing, but I successfully enabled identity platform on a non gsuite account.

**Comment by mikehelmick** [comment]
Anything left on this one?
