### ISSUE TITLE
Refactor VerificationCode.Validate to separate user error from system error

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1439]
At present, `VerificationCode.Validate` returns an error for user error (e.g. invalid symptom onset date) and system error (e.g. code too short).

We need to separate these out because, upstream, it's impossible to determine if we should return a 4xx or 5xx response. Gorm also swallows the concrete error types, so we can't switch on them. However, even if we could, things like checking valid test type already exist in the controller.

/cc @mikehelmick

**Comment by sethvargo** [comment]
@whaught for you to consider in your refactor

**Comment by whaught** [comment]
We wind up checking most things twice (which is weird) and don't expect .BeforeSave() to fire. The test-too-old for example is checked here for client error:
https://github.com/google/exposure-notifications-verification-server/blob/d29ee063c71cc705de136f3193862236ee270e9a/pkg/controller/issueapi/parse_date.go#L76
and then again here:
https://github.com/google/exposure-notifications-verification-server/blob/494b99e6db1b388ccf888aab25cdf5531c155b26/pkg/database/vercode.go#L235

**Comment by sethvargo** [comment]
Yea, I think we should explore moving all of this into the model if possible.
