### ISSUE TITLE
MT: Per realm signing keys

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#149]
### TL;DR

The token singing key can be shared by the whole server, as it is for internal consumption.

The certificate signing key should be set up on a per-realm basis.

Ideally we would just create this when the realm is created -added into tooling.
The "server" microservice needs to have signing key creation capabilities

/kind enhancement

**Comment by sethvargo** [comment]
Heh - I was just looking at stuff and thinking "why is this in-band of the request" 😄

**Comment by mikehelmick** [comment]
related to #93

**Comment by mikehelmick** [comment]
done.

filed on followup: https://github.com/google/exposure-notifications-verification-server/issues/349

/close
