### ISSUE TITLE
Track rate of expired code rejection

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#1497]
Some states wish to explain their user attrition rate. Once codes are received users may drop out of the flow (or never start it to begin with). We see lots of expired codes in the logs, it might be nice to gather data on our code rejection/accept rate and reason. This might help us understand user behavior, adjust code expiry, or encourage states to use long-codes rather than short for a longer expiry period

/assign

**Comment by sethvargo** [comment]
Duplicate of https://github.com/google/exposure-notifications-verification-server/issues/1232
