### ISSUE TITLE
Latency SLOs may be invalid

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1502]
We had a small spike in latency for 0.6s. All the SLO latency alerts continued to fire for over an hour, even after latency dropped to normal. Even an hour later, the SlowBurn graphs haven't dropped even though latency has been normal for a long time.

/cc @yegle @mariliamelo @yuriatgoogle

**Comment by sethvargo** [comment]
<img width="918" alt="screenshot-20201230-184248@2x" src="https://user-images.githubusercontent.com/408570/103386887-df007680-4ace-11eb-9344-955245e63dca.png">
<img width="865" alt="screenshot-20201230-184302@2x" src="https://user-images.githubusercontent.com/408570/103386889-df007680-4ace-11eb-9f4c-f4773b0beb66.png">

**Comment by yuriatgoogle** [comment]
I think deleting the alerting policies makes it so it's hard to see what all happened....

**Comment by sethvargo** [comment]
/close

We've refactored our policies
