### ISSUE TITLE
Hostname match not found (Multifactor Authentication) error

### ISSUE THREAD

**Issue by grpandurangipwc** [google/exposure-notifications-verification-server#1517]
### TL;DR

When I tried to register phone number in my account got this error
"Hostname match not found"

**Expected behavior**

My phone number has to get registered

**Observed behavior**

Got an error. Attached is the [error.]([url]([url](url

)))

### Reproduction

1. Login
2. In the right menu, go to "My Account"
3. Click Register phone
4. Provide display name and phone number and click register
5. It gives error

**Screenshots**

**Environment**

- OS:
- Browser:
- Version:

**Additional information**

**Comment by grpandurangipwc** [comment]
[](url)

**Comment by mikehelmick** [comment]
What environment did this occur in?

**Comment by grpandurangipwc** [comment]
encv-staging

**Comment by mikehelmick** [comment]
we don't support that environment - I cannot reproduce this on any environments that we support.

**Comment by grpandurangipwc** [comment]
But we are seeing this after updating to 0.19.0. So thought of brining to notice.

**Comment by sethvargo** [comment]
Can you please share the full error? All we see above is:

```text
Got an error. Attached is the [error.]([url]([url](url

)))
```

Did you mean to attach a screenshot?

I just tested against our 0.19 installations and cannot reproduce the issue.

**Comment by whaught** [comment]
I think this can happen if you have a custom domain and haven't added it to Firebase's list in:
firebase console under `authentication > sign-in providers` under `Authorized Domains`
That said I wouldn't expect to see a difference with 0.19.0 over previous versions

**Comment by mikehelmick** [comment]
this was a config issue. it is resolved

/close
