### ISSUE TITLE
Warning: Validation failed

### ISSUE THREAD

**Issue by grpandurangipwc** [google/exposure-notifications-verification-server#1562]
### TL;DR

On selecting the realm and then select "Users" in the dropdown menu, I see "Warning: Validation failed". 
This is not coming for all realms.

**Expected behavior**

Did not expect this warning. Users not listed. 

**Observed behavior**

Users page did not come up but showed this error instead. 

### Reproduction

1.  Created new realm
2. Selected the realm
2.  Clicked on "Users" in the dropdown menu

**Screenshots**

**Comment by grpandurangipwc** [comment]
Unable to attach the screenshot. Its not attaching.

**Comment by grpandurangipwc** [comment]
Was not able to reproduce it in regular pattern. Hence closing.

**Comment by sethvargo** [comment]
Is this still an issue? Can you please provide more information including a screenshot?

**Comment by sethvargo** [comment]
I was not able to reproduce this in local testing or in any of our testing environments. If you have more information, please include the environment name and timestamps.

/close

**Comment by grpandurangipwc** [comment]
This issue exists in encv-test as well. I guess the issue should be reopened.

**Comment by mikehelmick** [comment]
This is a a data issue specific to those environments where a user record as manually deleted.

We will be adding a DB migration to v0.20.0 to work around this if it were to be in any other environment.

/assign @sethvargo
