### ISSUE TITLE
Incorrect pagination numbers

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#1595]
This is the bottom of https://encv.org/admin/mobile-apps

![Screen Shot 2021-01-14 at 1 51 40 PM](https://user-images.githubusercontent.com/36240966/104653622-bbf9c900-566f-11eb-8ff9-8209c13acc44.png)

Some kind of integer overflow happening here?

/assign

**Comment by sethvargo** [comment]
It has been 0 days since integer overflow.
