### ISSUE TITLE
upon upgrade database migrations fails

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#161]
upon upgrading the codebase and running migrations.

Migrations failed with the following : 

[2020-07-31 17:26:25]  pq: duplicate key value violates unique constraint "users_pkey"; pq: current transaction is aborted, commands ignored until end of transaction block

**Comment by mikehelmick** [comment]
Do you have the line before that?
Indicating which migration it is

**Comment by sherifkozman** [comment]
@mikehelmick 
/exposure-notifications-verification-server/pkg/database/migrations.go:267)
[2020-07-31 17:26:25]  pq: duplicate key value violates unique constraint "users_pkey"; pq: current transaction is aborted, commands ignored until end of transaction block

**Comment by mikehelmick** [comment]
Any other log lines you can share?

It shouldn’t be adding any new users, just upgrade existing ones to the default realm.

You can redact user info or email me privately

**Comment by sherifkozman** [comment]
Here you go : 

`{"severity":"info","ts":1596241572.75421,"logger":"default","caller":"database/migrations.go:351","message":"database migrations started"}
{"severity":"info","ts":1596241573.8919392,"logger":"default","caller":"database/migrations.go:183","message":"db migrations: upgrading authorized_apps table."}
{"severity":"info","ts":1596241575.667299,"logger":"default","caller":"database/migrations.go:196","message":"db migrations: adding issuer columns to issued codes"}
{"severity":"info","ts":1596241577.437624,"logger":"default","caller":"database/migrations.go:212","message":"db migrations: adding sms_configs table"}
{"severity":"info","ts":1596241578.215978,"logger":"default","caller":"database/migrations.go:222","message":"db migrations: create realms table"}
{"severity":"info","ts":1596241579.8904,"logger":"default","caller":"database/migrations.go:227","message":"Create the DEFAULT realm"}
{"severity":"info","ts":1596241580.0886269,"logger":"default","caller":"database/migrations.go:237","message":"Add RealmID to Users."}
{"severity":"info","ts":1596241582.4763288,"logger":"default","caller":"database/migrations.go:241","message":"Join Users to Default Realm"}
{"severity":"info","ts":1596241582.525915,"logger":"default","caller":"database/migrations.go:247","message":"added user: 1 to default realm"}
{"severity":"info","ts":1596241582.5259562,"logger":"default","caller":"database/migrations.go:247","message":"added user: 3 to default realm"}
{"severity":"info","ts":1596241582.5259688,"logger":"default","caller":"database/migrations.go:247","message":"added user: 25 to default realm"}
{"severity":"info","ts":1596241582.52598,"logger":"default","caller":"database/migrations.go:247","message":"added user: 9 to default realm"}
{"severity":"info","ts":1596241582.5259871,"logger":"default","caller":"database/migrations.go:247","message":"added user: 10 to default realm"}
{"severity":"info","ts":1596241582.526,"logger":"default","caller":"database/migrations.go:247","message":"added user: 33 to default realm"}
{"severity":"info","ts":1596241582.52601,"logger":"default","caller":"database/migrations.go:247","message":"added user: 13 to default realm"}
{"severity":"info","ts":1596241582.526017,"logger":"default","caller":"database/migrations.go:247","message":"added user: 23 to default realm"}
{"severity":"info","ts":1596241582.526117,"logger":"default","caller":"database/migrations.go:247","message":"added user: 20 to default realm"}
{"severity":"info","ts":1596241582.526138,"logger":"default","caller":"database/migrations.go:247","message":"added user: 14 to default realm"}
{"severity":"info","ts":1596241582.526155,"logger":"default","caller":"database/migrations.go:247","message":"added user: 12 to default realm"}
{"severity":"info","ts":1596241582.5261672,"logger":"default","caller":"database/migrations.go:247","message":"added user: 15 to default realm"}
{"severity":"info","ts":1596241582.526177,"logger":"default","caller":"database/migrations.go:247","message":"added user: 18 to default realm"}
{"severity":"info","ts":1596241582.5261838,"logger":"default","caller":"database/migrations.go:247","message":"added user: 19 to default realm"}
{"severity":"info","ts":1596241582.52619,"logger":"default","caller":"database/migrations.go:247","message":"added user: 37 to default realm"}
{"severity":"info","ts":1596241582.526239,"logger":"default","caller":"database/migrations.go:247","message":"added user: 38 to default realm"}
{"severity":"info","ts":1596241582.5262458,"logger":"default","caller":"database/migrations.go:247","message":"added user: 4 to default realm"}
{"severity":"info","ts":1596241582.5262568,"logger":"default","caller":"database/migrations.go:247","message":"added user: 36 to default realm"}
{"severity":"info","ts":1596241582.526264,"logger":"default","caller":"database/migrations.go:247","message":"added user: 35 to default realm"}
{"severity":"info","ts":1596241582.5262709,"logger":"default","caller":"database/migrations.go:247","message":"added user: 34 to default realm"}
{"severity":"info","ts":1596241582.5262778,"logger":"default","caller":"database/migrations.go:247","message":"added user: 21 to default realm"}
{"severity":"info","ts":1596241582.5262852,"logger":"default","caller":"database/migrations.go:247","message":"added user: 7 to default realm"}
{"severity":"info","ts":1596241582.526363,"logger":"default","caller":"database/migrations.go:247","message":"added user: 5 to default realm"}
{"severity":"info","ts":1596241582.5263832,"logger":"default","caller":"database/migrations.go:247","message":"added user: 22 to default realm"}
{"severity":"info","ts":1596241582.5263932,"logger":"default","caller":"database/migrations.go:247","message":"added user: 8 to default realm"}
{"severity":"info","ts":1596241582.5264,"logger":"default","caller":"database/migrations.go:247","message":"added user: 24 to default realm"}
{"severity":"info","ts":1596241582.526408,"logger":"default","caller":"database/migrations.go:247","message":"added user: 6 to default realm"}
{"severity":"info","ts":1596241582.5264142,"logger":"default","caller":"database/migrations.go:247","message":"added user: 32 to default realm"}
{"severity":"info","ts":1596241582.526428,"logger":"default","caller":"database/migrations.go:247","message":"added user: 2 to default realm"}
{"severity":"info","ts":1596241582.526449,"logger":"default","caller":"database/migrations.go:247","message":"added user: 26 to default realm"}
{"severity":"info","ts":1596241582.526457,"logger":"default","caller":"database/migrations.go:247","message":"added user: 39 to default realm"}
{"severity":"info","ts":1596241582.526464,"logger":"default","caller":"database/migrations.go:254","message":"Add RealmID to AuthorizedApps."}
{"severity":"info","ts":1596241583.8843892,"logger":"default","caller":"database/migrations.go:263","message":"added auth app: app1.bt to default realm"}
{"severity":"info","ts":1596241583.884435,"logger":"default","caller":"database/migrations.go:263","message":"added auth app: app2.bt to default realm"}
{"severity":"info","ts":1596241583.884446,"logger":"default","caller":"database/migrations.go:263","message":"added auth app: app3.bt to default realm"}
{"severity":"info","ts":1596241583.8844538,"logger":"default","caller":"database/migrations.go:263","message":"added auth app: app4bt to default realm"}
{"severity":"info","ts":1596241583.8844612,"logger":"default","caller":"database/migrations.go:263","message":"added auth app: app5.bt to default realm"}
{"severity":"info","ts":1596241583.884469,"logger":"default","caller":"database/migrations.go:263","message":"added auth app:  to default realm"}

exposure-notifications-verification-server/pkg/database/migrations.go:267)
[2020-07-31 17:26:25]  pq: duplicate key value violates unique constraint "users_pkey"`

**Comment by mikehelmick** [comment]
Thank you - will try and replicate

**Comment by mikehelmick** [comment]
fix is out for review: https://github.com/google/exposure-notifications-verification-server/pull/162
