### ISSUE TITLE
Add non-paging alert for database backup failure

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-verification-server#1612]

**Comment by sethvargo** [comment]
The database backup service is a Cloud Scheduler job, so it should be alerting with CloudSchedulerFailed (which pages). Are you thinking we have a separate, non-paging alert?

**Comment by mariliamelo** [comment]
Correct, we are already being paged by Cloud Scheduler job. I'll drop since we can easily obtain this information by filtering logs with `resource.type="cloud_scheduler_job" severity=ERROR`
