### ISSUE TITLE
Make terraform work for upgrades

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#164]
initial deploy should use :latest instead of :initial

 allow CR services to redeploy - it's OK to require the ./scripts/build to be run, to update latest

DB migration is the tricky bit

/kind enhancement

**Comment by sethvargo** [comment]
I don't think we want to do this, similar to how we don't do this for the main server. Terraform barfs on Cloud Run revision numbers because the state's won't match. You have to _delete_ the resource to get it to re-deploy correctly with the right environment.
