### ISSUE TITLE
Add e2e-enx tests to run on presubmit 

### ISSUE THREAD

**Issue by mariliamelo** [google/exposure-notifications-verification-server#1699]
### TL;DR
We should refactor the code and make it possible to run e2e-enx tests on presubmit in order to save time. Currently we need to deploy the code again every time we make changes.

**Comment by mikehelmick** [comment]
Remember these tests cross server boundaries - so it would involve booting the key server exposure service, configured correctly.

**Comment by sethvargo** [comment]
The redirector does not require a key server.
