### ISSUE TITLE
Remove onboarding bits

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#1727]
Remove all the onboarding pieces. This should happen before we cut our next release to reduce churn.

**Comment by mikehelmick** [comment]
What does this mean?

**Comment by sethvargo** [comment]
We added all the ONBOARDING_DOMAIN and onboarding bits to the enx-redirector. It sounds like we're not doing that anymore.

**Comment by mikehelmick** [comment]
ah... those onboarding pieces :)
