### ISSUE TITLE
How do I create the initial system administrator?

### ISSUE THREAD

**Issue by krazykid** [google/exposure-notifications-verification-server#1794]
### Question
The [system admin guide](https://github.com/google/exposure-notifications-verification-server/blob/main/docs/system-admin-guide.md#account-setup) says that an existing system administrator can invite other system administrators. How do we create the initial system administrator? I can't seem to find this in the documentation. I've deployed the server, I just can't log in. 😕

Tagging: @jbigg

**Comment by mikehelmick** [comment]
Please see this section of the production doc:

https://github.com/google/exposure-notifications-verification-server/blob/main/docs/production.md#user-administration
