### ISSUE TITLE
Add Metrics and Tracing

### ISSUE THREAD

**Issue by icco** [google/exposure-notifications-verification-server#180]
### TL;DR

We want end to end tracing and metric support to match what's in https://github.com/google/exposure-notifications-server

**Comment by sethvargo** [comment]
Can we try to do this with middleware as much as possible? There will be exceptions, but I'm not a huge fan of how much non-core logic is in our handlers for the main server.

**Comment by icco** [comment]
yeah, definitely. Anything generic (ie not business specific metrics) will be in middleware.

**Comment by icco** [comment]
https://github.com/google/exposure-notifications-server/pull/846 also adds some stuff

**Comment by mikehelmick** [comment]
What's left here?

**Comment by icco** [comment]
I think we can close this for more specific bugs. https://github.com/google/exposure-notifications-verification-server/issues/266 and https://github.com/google/exposure-notifications-verification-server/issues/267
