### ISSUE TITLE
Cloud Load Balancer timeout

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#1829]
It looks like redis connection timeout is too long and caused Cloud Load Balancer timeout to forward the request, result in 504 response and triggered HostDown alert.

We should either increase the timeout on Cloud Load Balancer end so the latency on Cloud Run end (~25s) doesn't trigger 504 error, or reduce the redis connecting timeout to reduce the latency on Cloud Run end.

**Comment by sethvargo** [comment]
The redis connection timeout is 1s and the idle timeout is 1m. Is 1s too long for the glb?
