### ISSUE TITLE
error in database migration after latest update

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#213]
Updating from pre-Realm setup the database migration failed : 

```
Step #1 - "migrate": (/workspace/pkg/database/migrations.go:239)
Step #1 - "migrate": [2020-08-10 02:51:02]  pq: duplicate key value violates unique constraint "uix_realms_name"
Step #1 - "migrate": {"severity":"error","ts":1597027862.3047037,"logger":"default","caller":"database/migrations.go:519","message":"database migrations failed: pq: duplicate key value violates unique constraint \"uix_realms_name\"","stacktrace":"github.com/google/exposure-notifications-verification-server/pkg/database.(*Database).MigrateTo\n\t/workspace/pkg/database/migrations.go:519\nmain.realMain\n\t/workspace/cmd/migrate/main.go:58\nmain.main\n\t/workspace/cmd/migrate/main.go:36\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
Step #1 - "migrate": {"severity":"info","ts":1597027862.3055081,"logger":"default","caller":"migrate/main.go:43","message":"migrations complete"}
```

@mikehelmick

**Comment by sethvargo** [comment]
Hi @sherifkozman - is that failing on step 11? Can you set `DB_DEBUG=1` and re-run the migrations to share the output? It will include the raw SQL which will help diagnose this.

When we migration pre-realm -> realm, we move everything to a "default" realm. I believe that error is happening because you already have a "default" realm in the table somehow.

**Comment by sethvargo** [comment]
Ping

**Comment by sherifkozman** [comment]
Sorry it totally slipped in the notifications avalanche :) 

(/workspace/pkg/database/migrations.go:239)
[2020-08-14 21:36:35]  pq: duplicate key value violates unique constraint "uix_realms_name"
{"severity":"ERROR","timestamp":"2020-08-14T21:36:35.213977364Z","caller":"database/migrations.go:578","message":"database migrations failed: pq: duplicate key value violates unique constraint \"uix_realms_name\"","stacktrace":"github.com/google/exposure-notifications-verification-server/pkg/database.(*Database).MigrateTo\n\t/workspace/pkg/database/migrations.go:578\nmain.realMain\n\t/workspace/cmd/migrate/main.go:69\nmain.main\n\t/workspace/cmd/migrate/main.go:46\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
PUSH
DONE

hopefully this is clear enough as i broke the dev server :)

**Comment by sethvargo** [comment]
@sherifkozman do you happen to have a realm already named "default" or "Default"? Are you able to inspect the "realms" table?

**Comment by sherifkozman** [comment]
We do have a realm value "Default" that was set this way before Multi realms were intoduced

**Comment by sethvargo** [comment]
Yea, so that's why you're getting a migration issue. There's a uniqueness constraint on realm name. Can you rename your existing default to "default1" or something to remove conflicts? Alternatively, you can edit the migration step to lookup your realm and use it instead of creating a new one.

**Comment by sethvargo** [comment]
Actually, I found a way to make the migrations work for you.

**Comment by sherifkozman** [comment]
i tried running migrations once more, then i tried renaming realm and in both cases migrations failed with error "validation failed"

![Screen Shot 2020-08-15 at 1 07 39 PM](https://user-images.githubusercontent.com/666788/90320711-67072a80-def8-11ea-924d-69a61a2bfebf.png)
@sethvargo

**Comment by mikehelmick** [comment]
I'll be sending out a PR shortly that will fix the validation issue.

/assign

**Comment by sherifkozman** [comment]
Thanks @mikehelmick

**Comment by sherifkozman** [comment]
@mikehelmick ping 👍

**Comment by mikehelmick** [comment]
the fix is in #247

**Comment by sherifkozman** [comment]
Users were being added to the default realm as part of the latest fix however migration still fails verification as per the attached screenshot.

![Screen Shot 2020-08-17 at 7 28 44 AM](https://user-images.githubusercontent.com/666788/90407491-72269b80-e05b-11ea-9dcb-19a670012947.png)

**Comment by sethvargo** [comment]
Hi @sherifkozman are you sure you're on the latest code? Line 277 of migrations.go is an ending curly brace...

**Comment by sherifkozman** [comment]
@sethvargo you were right, there seems to be have been 2 commits 5 min appart.
However after pulling the latest commit to main the following verification error is still in place.
![Screen Shot 2020-08-17 at 7 45 04 AM](https://user-images.githubusercontent.com/666788/90409232-c03c9e80-e05d-11ea-997d-9f2279ec4de1.png)

**Comment by sethvargo** [comment]
That error is saying that validation failed for the authorized app. The only two validations are:

- name cannot be blank
- type must be one of "device" (0) or "admin" (1)

**Comment by sherifkozman** [comment]
There was an app with blank name that was accidently created over the earlier code and there was no way to delete it.
We removed it from the database and ran migrations again resulting the following error with uix_users_email

![Screen Shot 2020-08-17 at 9 16 16 AM](https://user-images.githubusercontent.com/666788/90418787-760dea00-e06a-11ea-9d17-b0e5688926c6.png)

**Comment by sethvargo** [comment]
That means you already have a violation on the index. The latest migrations make the index case-_in_sensitive. You most likely have users with the same email address and different capitalizations.

Previously this was valid:

- ID: 1, email: foo@bar.com
- ID: 2, email: FOO@BAR.COM

These are now treated as the same user and the index enforce case-insensitive uniqueness.
