### ISSUE TITLE
Stats screenshots missing from documentation?

### ISSUE THREAD

**Issue by ethanmdavidson** [google/exposure-notifications-verification-server#2170]
The screenshots of the statistics stuff seems to be missing from the docs: https://github.com/google/exposure-notifications-verification-server/blob/main/docs/realm-admin-guide.md#codes-issued-and-used

For example, one of the links used is https://github.com/google/exposure-notifications-verification-server/blob/main/docs/images/admin/stats01.png, which gives a 404. Lost in a reorganization perhaps?

**Comment by mikehelmick** [comment]
Assigning to @sethvargo who just redid the screenshots.
