### ISSUE TITLE
Clarify language around symptom date and test date

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#224]
### TL;DR

In the UI, symptom date should indicate to the user that they should enter the test date if they don’t know the symptom onset date.

/kind enhancement

**Comment by mikehelmick** [comment]
Another design option

Change the UI and API to accept both symptom date and test date and then when minting the verification token select the right one

1) symptom onset if exists
2) test date if provided and #1 doesn’t exist
3) leave blank if neither

I think this would reduce cognative load on case workers insteading of having to interprate a multi-use date field.

**Comment by sethvargo** [comment]
We could also default test date to today's date. Thoughts?

**Comment by mikehelmick** [comment]
we’d need to run that by the medical team. I think the directive was to leave it blank if neither was known
