### ISSUE TITLE
First User isnt created in the database upon fresh deployment

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#229]
After Running a fresh installation , first user to the default Realm gets created in firebase but doesnt get added into the database and doesnt get added or assigned to any realm

![Screen Shot 2020-08-13 at 3 25 02 PM](https://user-images.githubusercontent.com/666788/90193213-5b412a00-dd79-11ea-94e0-532c82703d8b.png)

**Comment by sethvargo** [comment]
Hi @sherifkozman - this is working as expected. You'll need to create the initial user using the `add-user` utility. Firebase doesn't "create" users - the default setting is to allow all (you can configure this in the firebase console), but then you have to create that user (by email) in the database using the add-user tool in this repo. Let me know if that helps.

**Comment by sherifkozman** [comment]
Yes we did add users and Realms through the cmd tools and got it going from there.
Please check #231 when you can
