### ISSUE TITLE
Testing /api/checkcodestatus results in unknown field UUID

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#234]
As we are testing the /api/checkcodestatus through the adminapi service URL and providing a JSON as per /pkg/clients/apis.go we get an error of : 
Error 400 : {"error":"unknown field \"UUID\"","error_code":""}

**Comment by whaught** [comment]
What's the request/url we're trying here?

This should be to `"/api/checkcodestatus"` with a body like:
`{ "uuid": ""}`

I've got a known issue where error response strings aren't shown properly: https://github.com/google/exposure-notifications-verification-server/pull/235

**Comment by sherifkozman** [comment]
@whaught this is exactly what we are trying and the result is : 
error 400 : {"error":"unknown field \"uuid\"","error_code":""}

URL is https://admin_api_host/api/checkcodestatus
