### ISSUE TITLE
Is User Report Tokens Claimed a subset of Tokens Claimed?

### ISSUE THREAD

**Issue by dte324** [google/exposure-notifications-verification-server#2350]
### Question
To elaborate, I presume the Tokens Claimed metric also includes token claimed from user reports. Is this correct?

Thanks!

**Comment by sethvargo** [comment]
Hi @dte324 

Yes, UserReportTokensClaimed is a subset of TokensClaimed. Please let us know if you have any additional questions.

**Comment by dte324** [comment]
Thank you @sethvargo
