### ISSUE TITLE
v1.16.0 tag points to the same commit as v1.15.0

### ISSUE THREAD

**Issue by Apisov** [google/exposure-notifications-verification-server#2386]
### TL;DR

[v1.16.0](https://github.com/google/exposure-notifications-verification-server/releases/tag/v1.16.0) is the same as [v1.15.0](https://github.com/google/exposure-notifications-verification-server/releases/tag/v1.15.0)

Also release branches for 1.16 and 1.15 are identical as well.

**Comment by sethvargo** [comment]
Hi @Apisov - thanks for raising this. @mikehelmick can you look into this?

**Comment by mikehelmick** [comment]
ack - I will get this fixed shortly.

**Comment by mikehelmick** [comment]
Fixed - Thanks for the report

https://github.com/google/exposure-notifications-verification-server/releases/tag/v1.16.1
