### ISSUE TITLE
Adding a new realm fails with verification failed error

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#260]
Adding a new realm through command line tool results error : 

(/verification-server/pkg/database/realm.go:308)
[2020-08-17 19:54:09]  validation failed
{"severity":"EMERGENCY","timestamp":"2020-08-17T19:54:09.466307-07:00","caller":"add-realm/main.go:50","message":"failed to create realm: validation failed","stacktrace":"main.main\n\t//verification-server/cmd/add-realm/main.go:50\nruntime.main\n\t/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:203"}
exit status 1

any pointers ?

**Comment by mikehelmick** [comment]
yeah - it's a one line fix. Sorry I missed that in my last change.

/assign

**Comment by sherifkozman** [comment]
No worries, its why we test things out :) 
👍

**Comment by mikehelmick** [comment]
I'll be adding the ability to create a realm via UI soon

**Comment by sherifkozman** [comment]
No worries, its all good, waiting for you multi tenant updates as well
