### ISSUE TITLE
Clarification for AppName value when creating Admin and Device APIs

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#263]
When creating a new API key (Device/Admin) , if appname is supposed to be the bundleID/AppID (i.e com.appname.mobile) , system refuses using the same app name even if API type is different (i.e Device Vs Admin)
" Failed to create API Key: pq: duplicate key value violates unique constraint "realm_apikey_name" "
Is this a correct behavior ?

**Comment by mikehelmick** [comment]
Yes - API key names must be unique.

**Comment by sherifkozman** [comment]
@mikehelmick they must be unique but it doesnt have to be the app ID , did i get that correct ?

**Comment by mikehelmick** [comment]
Right - it’s just a string - something an admin can identify should you need to revoke a key
