### ISSUE TITLE
Open Census for Postgresql

### ISSUE THREAD

**Issue by icco** [google/exposure-notifications-verification-server#267]
### TL;DR

Implement https://opencensus.io/integrations/sql/go_sql/

**Comment by sethvargo** [comment]
Re-opening this. We had to revert the OC integration because it was introducing quite a few test failures and legitimate data races in our tests.

**Comment by sethvargo** [comment]
I'm pretty sure that we can instrument postgres and then pass the postgres driver to gorm. Then we just have to tell gorm to use the context that has opencensus configured. 

I think the library we pulled in was doing some hacky things with gorm callbacks.

**Comment by taddari** [comment]
Yes, I think that library is the culprit, let me revert that.

**Comment by taddari** [comment]
Hi, Seth, yes I that library was unnecessary as I couldn't see any gorm related metrics anyways. By the way, for this we actually don't need to pass any context as we are not doing any tracing anyways. Just overriding the driver is enough to show the metrics in my opinion.
