### ISSUE TITLE
Realm onboarding docs

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#268]
Write a doc for how to onboard as a user of a realm

/kind enhancement

**Comment by sethvargo** [comment]
@mikehelmick is this done with https://github.com/google/exposure-notifications-verification-server/blob/main/docs/realm_guide.md or were you thinking about something more specific?

**Comment by mikehelmick** [comment]
yeah, I guess this is done.

/assign
/close
