### ISSUE TITLE
No prompt for new users to create password

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#296]
After Adding a new user , the login page has got username/password fields with no workflow for new users to set up passwords like before.

I assumed there will be an email sent out when adding new users but there was non

**Comment by mikehelmick** [comment]
This is still under development

/assign @whaught

**Comment by whaught** [comment]
This is on the way! We removed the firebaseUI login to make way for 2-factor auth. We now require email validation too.

**Comment by sherifkozman** [comment]
Thanks @whaught but after deploying the latest code we were unable to add new users as they are unable to create passwords.
Any ETA for when would that be completed ?

**Comment by whaught** [comment]
I believe with https://github.com/google/exposure-notifications-verification-server/pull/298 they should be able to click 'new user' and create their login using the old flow
