### ISSUE TITLE
Cache database user reads

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#30]
https://github.com/google/exposure-notifications-verification-server/pull/27#discussion_r441908612

**Comment by odeke-em** [comment]
I see per https://github.com/google/exposure-notifications-verification-server/blob/5f60f06db86ccabcc5e7ca71e12288060f93fdd7/README.md#L48 we already use Redis as the rate limiter. That makes it the clear choice then for this task too.

**Comment by mikehelmick** [comment]
Yeah, we already have a Redis instance in the mix, so that is a safe choice.

I think it's fine to move forward with that and have the caching disabled by default (dev instance)

**Comment by sethvargo** [comment]
Yea, generic read-through cache. The reason I haven't been tackling this is because all the redis libraries for Go have various tradeoffs and I haven't had time to weigh them.

**Comment by odeke-em** [comment]
Not a problem, I've got y'all :) I examined a bunch of the libraries and I have used redigo by Gary Burd, and even rolled out an instrumented version of it https://godoc.org/github.com/opencensus-integrations/redigo/redis. I'll send a PR for it.

SGTM, turned off by default works.

**Comment by sethvargo** [comment]
This is done!
