### ISSUE TITLE
Redis connect is not always live on boot

### ISSUE THREAD

**Issue by icco** [google/exposure-notifications-verification-server#344]
### TL;DR
We use redis for rate limiting. Sometimes when we are deploying a new version, and we are sending lots of traffic, we see connection drops to Redis, thus returning 500s to the user.

**Expected behavior**

429 or 200 response code (ie Redis stays alive)

**Observed behavior**

500

### Reproduction

If you send a lot of traffic to the service while you are promoting a new version, you'll see a failure. We believe the failure is coming from the old version, not the new version.

**Comment by mikehelmick** [comment]
Do we still see this w/ the latest changes?

**Comment by icco** [comment]
I believe this is fixed now.
