### ISSUE TITLE
CACHE_REDIS_HOST broken

### ISSUE THREAD

**Issue by joshgummersall** [google/exposure-notifications-verification-server#405]
### TL;DR
The way env prefixing is used in the current repo for cache configuration is broken. `CACHE_` is included as a prefix twice for Redis host/port environment variables.

**Expected behavior**
Services with caching should work with the provided Terraform configuration

**Observed behavior**
Services with caching do not work.

### Reproduction
Deploy from master

The fix should be to either remove the dupe `env:", prefix="CACHE_"` from the Redis cache config or to remove the prefix everywhere `cache.Config` is referenced.

**Comment by joshgummersall** [comment]
The acute fix I used was the change `CACHE_REDIS_HOST` to `CACHE_CACHE_REDIS_HOST` in Terraform files.

**Comment by sethvargo** [comment]
Dupe of https://github.com/google/exposure-notifications-verification-server/issues/400. Although that should have been already fixed depending on when you pulled.

**Comment by sethvargo** [comment]
Fixed in https://github.com/google/exposure-notifications-verification-server/issues/402. Please ensure you're on that commit or later.

**Comment by joshgummersall** [comment]
Probably landed just after I pulled and deployed. Thanks!
