### ISSUE TITLE
Required redis envvar is not added to Terraform configs

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#407]
See https://github.com/google/exposure-notifications-verification-server/blob/main/pkg/redis/config.go

**Comment by sethvargo** [comment]
What envvars are missing?

**Comment by sethvargo** [comment]
They are set for the [cacher](https://github.com/google/exposure-notifications-verification-server/blob/5824e7f1110fee4b34163e866c2b17b8f474b35a/terraform/services.tf#L30-L31) and the [rate limiter](https://github.com/google/exposure-notifications-verification-server/blob/5824e7f1110fee4b34163e866c2b17b8f474b35a/terraform/services.tf#L66-L67)

**Comment by yegle** [comment]
Ooops, you are right. Apparently `terraform apply` failed on my end. Rerun `terraform apply` fixed the issue.

**Comment by yegle** [comment]
FWIW I think this is the same issue https://github.com/google/exposure-notifications-verification-server/pull/402 fixes.

**Comment by yegle** [comment]
Hmm there's something that still isn't right.

I'm working on main branch. Deploying the verification server and check the adminapi service's detail I can see these environment variables:

```
        - name: CACHE_REDIS_ADDRESS
          value: 10.7.1.4:6379
        - name: CACHE_TYPE
          value: REDIS
```

E2e test is failing with this log:

```
jsonPayload: {
  caller: "limitware/middleware.go:160"   
  error: "connection is not usable: dial tcp 127.0.0.1:6379: connect: connection refused"   
  logger: "ratelimit"   
  message: "failed to take"   
  stacktrace: "github.com/google/exposure-notifications-verification-server/pkg/ratelimit/limitware.(*Middleware).Handle.func1
	github.com/google/exposure-notifications-verification-server/pkg/ratelimit/limitware/middleware.go:160
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2042
github.com/google/exposure-notifications-verification-server/pkg/controller/middleware.RequireAPIKey.func1.1
	github.com/google/exposure-notifications-verification-server/pkg/controller/middleware/apikey.go:92
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2042
github.com/google/exposure-notifications-verification-server/pkg/controller/middleware.AddHSTS.func2.1
	github.com/google/exposure-notifications-verification-server/pkg/controller/middleware/hsts.go:47
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2042
github.com/gorilla/mux.(*Router).ServeHTTP
	github.com/gorilla/mux@v1.7.4/mux.go:210
github.com/gorilla/handlers.loggingHandler.ServeHTTP
	github.com/gorilla/handlers@v1.4.2/logging.go:45
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP
	go.opencensus.io@v0.22.4/plugin/ochttp/server.go:92
net/http.serverHandler.ServeHTTP
	net/http/server.go:2843
net/http.(*conn).serve
	net/http/server.go:1925"   
  timestamp: "2020-08-28T05:18:58.112238241Z"   
 }
```

Version v0.5.0 works fine.

**Comment by yegle** [comment]
FWIW the parent of my branch is e3b8ca8eed858ed791bb4c823faa2e631d52f565

**Comment by sethvargo** [comment]
The values are `CACHE_REDIS_HOST` and `CACHE_REDIS_PORT`: https://github.com/google/exposure-notifications-verification-server/blob/e3b8ca8eed858ed791bb4c823faa2e631d52f565/terraform/services.tf#L28-L32
