### ISSUE TITLE
Realm level stats

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#410]
### TL;DR

Add charts AND graphs of how many codes a realm has issued per day.

Bonus points for graphing against number of codes that were claimed.

/assign @jeremyfaller 
/kind enhancement

**Comment by sethvargo** [comment]
Here's how we do it for users:

- https://github.com/google/exposure-notifications-verification-server/blob/e3b8ca8eed858ed791bb4c823faa2e631d52f565/pkg/controller/user/show.go#L63
- https://github.com/google/exposure-notifications-verification-server/blob/e3b8ca8eed858ed791bb4c823faa2e631d52f565/cmd/server/assets/users/show.html#L89

The users_stats table has a realmID, but the authapp_stats table does not. We'll probably need to join the authapp_stats table with the authapp table to get the realm ID.

**Comment by sethvargo** [comment]
/assign

Gonna fix up the last remaining bits since Jeremy is OOO this week.

**Comment by sethvargo** [comment]
Dunno why this didn't auto-close. Done.
