### ISSUE TITLE
set custom domain for firebase email verification

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#425]
### TL;DR
Ability to setup custom domain for firebase email verification and communication

**Additional information**
Currently all email communication for the verification server uses the projectid.firebaseapp.com as an email host, it would helpful to use custom domains for sending out email communication.

**Comment by sethvargo** [comment]
Hi @sherifkozman 

Unfortunately this process is not easily automated. You can configure this yourself in the firebase console. Here's an article with step-by-step instructions: https://medium.com/@arutkayb/firebase-auth-how-to-set-up-a-custom-domain-for-email-templates-1693999224be
