### ISSUE TITLE
Add system level twilio config that a system admin can 'share' with a realm

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#432]
/kind enhancement

**Comment by jeremyfaller** [comment]
Alright, getting started on this, and need some clarification: How are we looking to share this file? Is it the defaults loaded into a new realm, can a running realm be updated to the settings?

Can you walk me through a little of what you have in mind, and I'll fill in the more details?

**Comment by sethvargo** [comment]
Right now there's an "SMSConfigs" table that has a 1-1 mapping with a realm. The easiest thing to do would be to create a "system" realm where a sysadmin can upload some twilio creds using the existing forms, then provide a way to attach that SMSConfig to another realm (changing the relationship from 1-1 to 1-n)

**Comment by jeremyfaller** [comment]
And we should still allow a realm to its own config, correct? (So, a realm would have the system level config unless it overrides it, correct?)

**Comment by sethvargo** [comment]
Yea, I think the precedence is realm-specific, then system-specific (if shared with that realm, else empty (no sms)

**Comment by mikehelmick** [comment]
I'm encouraging realm operators to bring their own twilio credentials, but it's possible a system operator would want to just provide that.
