### ISSUE TITLE
Upgrade to Go 1.15.1

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#441]
https://groups.google.com/g/golang-announce/c/8wqlSbkLdPs/m/UccMwBPUBAAJ

**Comment by sethvargo** [comment]
/assign @jeremyfaller 

Note: we'll need to wait for the official Docker containers _and_ Homebrew to be updated.

**Comment by jeremyfaller** [comment]
FYI As of Sept 3, 2020 brew is not at 1.15.1.

**Comment by sethvargo** [comment]
Looks like it might have landed now.

**Comment by icco** [comment]
+1 landed for me as well.

**Comment by sethvargo** [comment]
I think Jeremy is out this week, so I'll pick this up.

/assign
