### ISSUE TITLE
cloud build step fails with 404 on save-cache

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#449]
cloud build services fail in step#2 save-cache with the following 404 error
Step #2 - "save-cache": failed to walk files: failed to write tar: googleapi: Error 404: Not Found, notFound: failed to close tar writer: googleapi: Error 404: Not Found, notFound: failed to close gzip writer: googleapi: Error 404: Not Found, notFound: failed to close gcs writer: googleapi: Error 404: Not Found, notFound
Step #2 - "save-cache":
Finished Step #2 - "save-cache"
ERROR
ERROR: build step 2 "us-docker.pkg.dev/vargolabs/gcs-cacher/gcs-cacher:0.1" failed: step exited with non-zero status: 1

**Comment by sethvargo** [comment]
You're missing the Cloud Storage cache bucket. Run the updated Terraform and then attempt to deploy.

**Comment by sherifkozman** [comment]
Did that and failed due to a missing container image was not found :
 
Error: Error waiting to create Service: resource is in failed state "Ready:False", message: Image 'gcr.io/gaen-verification/github.com/google/exposure-notifications-verification-server/e2e-runner:initial' not found.

**Comment by sethvargo** [comment]
Hmm yea, we added a new container and should have added this to the release notes. Run `terraform taint null_resource.build`.

**Comment by sherifkozman** [comment]
terraform taint null_resource.build worked
However e2e service fails to be created as it requires migration to run first as a dependency.

I ran migrations manually and this resolved the issue for now

**Comment by sethvargo** [comment]
I've updated the release notes for 0.6.0 to call this out. Unfortunately there's no easy way around it for now.
