### ISSUE TITLE
Create a stackdriver dashboard pulling in metrics from both key server and verification server

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#460]
### TL;DR
Now that #265 is fixed, we should set up some stackdriver dashboard showing the related metrics that are probed by the e2e-runner service.

### Design

1. Use https://www.terraform.io/docs/providers/google/r/monitoring_dashboard.html to manage the dashboards
2. Pull in metrics from both key server and verification server.

**Comment by icco** [comment]
We'll probably want two dashboards. One that's just verification server, and one that's for the e2e that has both.

**Comment by yegle** [comment]
Still working on this.

**Comment by yegle** [comment]
This is likely not needed (or not urgent enough to have it). I'll close this for now.
