### ISSUE TITLE
Use Terraform to manage our alerting rules

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#461]
### TL;DR
Similar to #460, we should also manage our alerting rules using Terraform so that the work can be replicated easily.

### Design

Use https://www.terraform.io/docs/providers/google/r/monitoring_alert_policy.html to manage alerting policies in StackDriver.

**Comment by sethvargo** [comment]
> alerting policies in StackDriver.

alerting policies in the _product formerly known as_ StackDriver.

**Comment by icco** [comment]
There are two alerts we should write:

 - Elevated 5xx
 - Elevated rate limited requests

I've got the 5xx if you want to write the rate limit one @yegle ?

**Comment by yegle** [comment]
Sure I can take the rate limit requests one.

**Comment by yegle** [comment]
Consider this fixed.
