### ISSUE TITLE
Creation of alerting Policies will fail because monitoring workspace must be manually enabled

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#477]
### TL;DR
Creation of alerting Policies will fail because monitoring workspace must be manually enabled.

### Details : 
GCP Monitoring Workspace have no support in terraform yet and should be enabled manually first before running the Alerting and notifications terraform scripts.

README should be updated to include such note and manual step of enabling a monitoring workspace.

**Comment by icco** [comment]
/assign @yegle 

We discovered this yesterday! Thanks for filing this, @yegle is working on it.

**Comment by yegle** [comment]
Yes unfortunately the only way to create the workspace is to go to the Google Cloud console (it's not even supported in gcloud command per the document, otherwise we would be able to create it by using `null_resource` with `local-exec`).

**Comment by sherifkozman** [comment]
Yes this is why my suggestion is only update the readme with this note as a prerequisite in case alerting is enabled

**Comment by sethvargo** [comment]
@yegle @icco can you send me an email with the details? I might be able to poke the team and see where this is on the roadmap.

**Comment by yegle** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/2605 is the one tracking this feature.

It looks like https://github.com/hashicorp/terraform-provider-google/issues/6384 is the internal bug tracking it :-)

**Comment by sherifkozman** [comment]
I still don't get hour it's a terraform bug if GCP doesn't avail any api to create/assign workspaces for stackdriver yet.

**Comment by sethvargo** [comment]
Such an API might exist and it might be in alpha.
