### ISSUE TITLE
In a Multi tenant setup, how is the first sys admin created?

### ISSUE THREAD

**Issue by sherifkozman** [google/exposure-notifications-verification-server#478]
Deploying the latest release on a fresh install not an upgrade, doesnt seem clear how the first Realm Admin is being provisioned?

**Comment by mikehelmick** [comment]
You need to use ‘cmd/add-users’ to create system admins

**Comment by mikehelmick** [comment]
@sethvargo - what’s your plan? Just docs?

**Comment by sethvargo** [comment]
Yea, just docs
