### ISSUE TITLE
Allow realms to require 2FA

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#506]
### TL;DR

All realms to require 2FA before users can issue codes.

/kind enhancement
/assign @whaught

**Comment by whaught** [comment]
The trouble is we are using the following from our server: https://pkg.go.dev/firebase.google.com/go/v4/auth
However I don't believe any such golang client library exists for Identity Platform https://cloud.google.com/identity-platform/docs/admin/manage-mfa-users#before_you_begin. The REST API is backwards compatible from but we need the added the 'multiFactor' field.

Looks like it can all be done in node.js and they are guiding folks to use Functions. Confusing - still looking around.

**Comment by whaught** [comment]
Sure enough: https://github.com/firebase/firebase-admin-node/blob/f11aed754d30fabb2b936e9b8958669c65750f5f/src/auth.d.ts#L217

Not present in other clients: https://github.com/firebase/firebase-admin-go/blob/cef91acd46f2fc5d0b3408d8154a0005db5bdb0b/auth/user_mgt.go#L71
