### ISSUE TITLE
in which scenario will we need authorizedapp?

### ISSUE THREAD

**Issue by laurentsimon** [google/exposure-notifications-verification-server#53]
authorizedapp is set in [apikey.go#L79(]https://github.com/google/exposure-notifications-verification-server/blob/main/pkg/controller/middleware/apikey.go#L79) but never read or checked.

I'm curious in which scenarios an actual implementation may use it? I don't think a server implementation would want to differentiate between different apps when storing the keys in the database - as it may provide a signal to de-anonymize users.

So probably used for statistics?

**Comment by mikehelmick** [comment]
this is now being used - we use it to load the effective realm w/ the new multi-tenancy feature.
