### ISSUE TITLE
Some metrics from ratelimit middleware are missing from Cloud Monitoring

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#535]
### TL;DR
Some of the metrics from the ratelimit middleware is missing from Cloud Monitoring's metrics explorer. This is causing `terraform apply` error when applying the dashboards.

Metrics missing from our test project:
- /key_errors_count

Metrics missing from our prod project:
 - /key_errors_count
- /rate_limited_count

**Expected behavior**
All 4 metrics defined in https://github.com/google/exposure-notifications-verification-server/blob/main/pkg/ratelimit/limitware/middleware.go is visible in Cloud Monitoring's Metrics explorer.

**Observed behavior**
Some are missing.

/cc @icco

**Comment by icco** [comment]
My current theory is that metrics that haven't been written to don't get populated.

**Comment by yegle** [comment]
Noticed from the doc https://cloud.google.com/monitoring/custom-metrics/creating-metrics:

> You can write data only to custom metric types. To write your data, use the timeSeries.create method. If the time series already exists, this method appends a new data point to the existing time series. If the time series does not exist, this method creates it and appends the data.

This sounds to me that the "failed to export metrics" error in #474 (maybe also #416?) is the root cause.

**Comment by icco** [comment]
Pretty sure this is a dupe of #474.

/duplicate

**Comment by yegle** [comment]
Confirmed the missing metric is now in Metrics Explorer!
