### ISSUE TITLE
Improve 2FA SMA enrollment

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#545]
### TL;DR

We have user reports that 2FA enrollment is difficult due to the JS dialog box.

Move the confirmation to a separate page.

/kind enhancement

**Comment by whaught** [comment]
the window.prompt for pin isn't ideal (it was the fastest thing to write for now)

**Comment by whaught** [comment]
/assign

I'm stealing this. @sethvargo yell at me if you've already got progress here

**Comment by sethvargo** [comment]
Steal away
