### ISSUE TITLE
Set up monitoring and alerting when realms are at certain capacity levels

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#572]
Set up monitoring and alerting when realms are at certain capacity levels (e.g. 90%). These will have to go to the server operators since we don't have a way to send email to realm admins.

There are already stats - we just need the monitoring and alerts.

/cc @icco @yegle - do one of you have capacity to work on this?

**Comment by icco** [comment]
/kind enhancement

I will next week, @yegle I think will too. And @femnad might also be free.
