### ISSUE TITLE
Add latency alerts

### ISSUE THREAD

**Issue by icco** [google/exposure-notifications-verification-server#577]
We should have p90 latency alerts for server and apiserver

**Comment by taddari** [comment]
I have decided to add GCLB https/backend_latencies for alerting
https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring#metric_reporting_frequency_and_retention
We actually don't have p90 aligner, but we have p95 https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.alertPolicies#aligner

@icco What should an ideal p95 alerting threshold? Does 5s sounds all right?

**Comment by icco** [comment]
Let us set it to 2s for 5m. Looking at the past week on our staging server, we're way below that.

![Screen Shot 2020-09-21 at 15 36 47](https://user-images.githubusercontent.com/20201/93812958-5b5a0280-fc20-11ea-92c6-b0deb8d4043f.png)

**Comment by taddari** [comment]
Sounds good. Will do that.
