### ISSUE TITLE
redirect service support associated domain

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#580]
The redirect service needs to support hosting the Apple associated domains data.
https://developer.apple.com/documentation/safariservices/supporting_associated_domains

And Android App Links ownership
https://developer.android.com/training/app-links/verify-site-associations

/kind enhancement

**Comment by jeremyfaller** [comment]
So, after digging into this, here's what I've figured out:

1) All the realm redirection services require lots of per-app data. Eg, iOS requires the appID, android requires the appID and a SHA fingerprint.
2) Configuring this data with command-line options probably won't work (the server would need to be rebooted for each android app update, etc.)

So, unless there's lots of argument, here's what I was going to propose:

1) Add new fields to the `authorized_apps` table, specifying things required, like the app package names, SHAs, etc.
2) Update the redirection server to use the tables from the DB.

If we bother to insert this stuff into the DB, we might as well update the redirect service to not just use the config-map.

Anyone have any thoughts here? Is there a simpler approach I'm not thinking of?

**Comment by flagxor** [comment]
Have you considered generating a static page with Javascript on it to do the redirect?
