### ISSUE TITLE
Change defaults for SMS templates for HTTPS redirect service

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#582]
1. For Non-EN Express, Change the default SMS text template to not include a clickable link

1. Change the expansion of [enslink]

    * Add a system level config, redirect TLD, i.e. `example.com`

    * Expand this link correctly in the https style.

/kind enhancement
/assign

**Comment by sethvargo** [comment]
@mikehelmick wanna wrap up #536 in this too?

**Comment by mikehelmick** [comment]
will do
