### ISSUE TITLE
Password reset link forces password reset

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#600]
When clicking on the password reset link, I'm taken to `/login/select-password`. Then, after a brief moment, I'm redirected to the "you must change your password" page.

![ezgif-1-f2554508ac13](https://user-images.githubusercontent.com/408570/93686316-73484f80-fa83-11ea-88b1-fd566704efb6.gif)

**Comment by whaught** [comment]
well that doesn't sound right. Thanks for the repro .gif - that's very clear
