### ISSUE TITLE
Delete User if removed from all realms

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#606]
### TL;DR
Currently deleting a user removes the current realm from their User entry

**Proposal**
If a user has no realms and has not been modified for ~30 days (configurable), the system should delete their database entry.

The cleanup job should **not** do this in real-time: when the last realm is removed, an admin may be adding them to another one.

**Alternatives considered**
Instead of deleting we could remove/scramble User PII data. We would do this if the record is important for maintaining any sort of auditability.

**Comment by sethvargo** [comment]
I think we should talk about this more in standup/chat. I'm worried about auditing requirements and deleting users.

**Comment by whaught** [comment]
Sure thing - I think it's worth discussing one way or the other.

**Comment by mikehelmick** [comment]
re: auditing - are you suggesting we just keep the user records around longer?

the user-stats is the only thing we would possibly lose, but I don't think those are accessible once the user has been removed from the realm already.

**Comment by sethvargo** [comment]
I'm thinking about the requirements we got from certain states.

**Comment by mikehelmick** [comment]
Nothing actionable there yet.

**Comment by sethvargo** [comment]
Do we still want to do this? I brought this up to @whaught in chat, but I'm worried about a situation where someone is using a shared Firebase account (e.g. shared among multiple login systems) and they want to disable that person's access to ENVS. It feels weird that ENVS would disable their overall account in that parent authentication system.

If we integrated directly with SAML, for example, I wouldnt want ENVS to delete the user from my internal IDP.

**Comment by whaught** [comment]
I agree with your point about the auth entry. I hadn't considered sharing auth with this system and others. That said we still might want to delete the ENVS User entry after a time.
