### ISSUE TITLE
Settings refactor - dropped SMS configs

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#620]
### TL;DR

With the refactor to realm settings on different pages - SMS configs are being dropped when editing info on other pages.

**Expected behavior**

SMS settings stay

**Observed behavior**

SMS settings dissapear

### Reproduction

1.  Ensure SMS settings are there (Twilio creds)
2.  Go to "codes" setting page - press save (don't need to actually change anything)
3.  navigate back to SMS tab, observe twilio creds are gone.

/assign @sethvargo

**Comment by sethvargo** [comment]
https://github.com/google/exposure-notifications-verification-server/pull/622
