### ISSUE TITLE
Flash not showing on signout

### ISSUE THREAD

**Issue by whaught** [google/exposure-notifications-verification-server#629]
### TL;DR
We used to wait 3 seconds to redirect from the /signout page. This is enough time to read error flashes - now the flash is displayed and we immediately redirect.

We could consider a way to hang on to the session flash and carry-forward in middleware or bake signout into login to eliminate the redirect

**Comment by sethvargo** [comment]
If we can move all the auth and signout to server-side, this problem goes away too 😄
