### ISSUE TITLE
nicer telephone widget

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#649]
provide a drop down for international telephone input

possibly using: https://github.com/jackocnr/intl-tel-input

code issue is more important, SMS / MFA handling second.

let the realm set a default

/kind enhancement

**Comment by sethvargo** [comment]
Heh - I was gonna use that exact thing 😄

**Comment by whaught** [comment]
Nice! I looked at that widget too for MFA...

**Comment by sethvargo** [comment]
Did you mean widght? (making fun of Mike)

**Comment by whaught** [comment]
Reopening. I'm going to try to apply the same to the MFA registration UI

**Comment by sethvargo** [comment]
Ah - I totally missed the "SMS/MFA is second" part.
