### ISSUE TITLE
Use an actual ISO region/subregion list to validate region codes

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#693]
Currently, we just do pattern validation (2-3)

It would be good to validate these against an actual list.

/kind enhancement

**Comment by sethvargo** [comment]
I'm -1 on this. As far as I can tell, the downside of someone putting in an invalid ISO code is that ENX redirects won't work. I think the toil and maintenance burden of curating and maintaining such a list exceeds value we get by adding such strict validation.

**Comment by mikehelmick** [comment]
that's fine - this hasn't in practice been an issue yet. ENX won't work if there is a mismatch and the actual config MUST be a valid ISO before it will be accepted by apple+google.

**Comment by mikehelmick** [comment]
I'm actually going to remove the validation and require not empty
This is breaking too many things in test

**Comment by sethvargo** [comment]
😄
