### ISSUE TITLE
SMS selector is not full width

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#711]
This is likely the CSS of the plugin, but it's really obvious on the MFA page:

<img width="449" alt="screenshot-20200929-150624@2x" src="https://user-images.githubusercontent.com/408570/94604258-68e93b00-0265-11eb-90b4-8d4a9778f17c.png">

The height/padding is also slightly off.

**Comment by whaught** [comment]
I noticed that. The plugin seems to apply its own style and I wasn't sure how to stop that. Alternatively we could make the display name box match its style for consistency

**Comment by sethvargo** [comment]
It's the same on the code issue page, just less obvious. I think we need to drop in some `!important`s
