### ISSUE TITLE
Add metrics to cleanup jobs

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#716]
Publish metrics for all things in the cleanup job including users, audits, etc.

Refs: https://github.com/google/exposure-notifications-verification-server/pull/705#discussion_r497483365

**Comment by sethvargo** [comment]
@icco metrics are in. Gonna repurpose this issue to be about dashboarding/alert.

**Comment by icco** [comment]
Sweet. Don't think we need an alert, just a dashboard graph.

**Comment by sethvargo** [comment]
/close 

this is done
