### ISSUE TITLE
Unable to delete the DB due lifecycle destroy param in production setup

### ISSUE THREAD

**Issue by grpandurangipwc** [google/exposure-notifications-verification-server#768]
### TL;DR

Unable to delete the DB due to prevent_destroy parameter has been set has true in production setup

```
 lifecycle {
    # This prevents accidental deletion of the database.
    prevent_destroy = true
  }
```

### Design

**Proposal**

```
var.prevent_destory {
    type = string
   default  = true
} 

  lifecycle {
    # This prevents accidental deletion of the database.
    prevent_destroy = var.prevent_destroy
  }
```

**Alternatives considered**

**Resources**
- [Link to documentation](TODO)
Manually delete the SQL

**Additional information**

**Comment by sethvargo** [comment]
We've had to revert this change. Terraform does not support configuring prevent_destroy via a variable.
