### ISSUE TITLE
Deduplicate metrics

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#773]
In many (all?) places, we are using two separate metrics to count failed/successful states. E.g. we have `code_issued_count` and `code_issue_error_count` [here](https://github.com/google/exposure-notifications-verification-server/blob/44a426a524442aedc164f3f2a7df809adb55c3cf/pkg/controller/issueapi/metrics.go#L60-L72).

Having two metrics makes it impossible to calculate an error ratio which is a very important metric to monitor. And we will need to add more metrics if we want to further break down what caused the error.

Instead we should have a single `code_issued_count` metric, with additional labels like `error_reason` (short text on why it failed) and `blame` (whether the failure is to blame the client or the server). This, together with the realm id information that we already have, allows us to setup flexible alerting rules:

- Overall `blame=server` error rate/ratio increase
- Per-realm-id `blame=client` error rate/ratio increase
- One particular `error_reason` rate/ratio increase

**Comment by sethvargo** [comment]
@yegle I know you've done a lot of work on this - are there specific remaining items you'd like to finish before closing this out?

**Comment by yegle** [comment]
Yes I want to use the new metrics in the alert policies. One of the blocking issue is Terraform lack support to define alert using MQL.

I'll do a review and close this, then track defining alerts using MQL in a separate issue.
