### ISSUE TITLE
Token for further publishing

### ISSUE THREAD

**Issue by jendakol** [google/exposure-notifications-verification-server#791]
### Question
In [the keys publishingdiagram](https://camo.githubusercontent.com/3cc17140e3236f29d0216e40624bebc9779ea962/68747470733a2f2f646576656c6f706572732e676f6f676c652e636f6d2f616e64726f69642f6578706f737572652d6e6f74696669636174696f6e732f696d616765732f766572696669636174696f6e2d666c6f772e737667) and also in [Publishing keys description](https://google.github.io/exposure-notifications-server/getting-started/publishing-temporary-exposure-keys), there's stated:
```
One of the fields of the publish request is the revisionToken. The revision token ... must be passed to the
server again, if the same device wants to either upload additional TEKs later or revise the status of TEKs
already uploaded.
```
In the diagram, this is the bottom part, as I understand it.

The problem is that there is a `nextKey-token` mentioned - and it's unclear where can one get it. Signing of first key batch (6) is done fine, but when I try to use the _long-term token_ (exchanged for VC) again in (10) it fails with `verification token invalid` error.

According to the diagram, the `nextKey-token` should come in the certificate response (7) but only the certificate itself is returned.

Please help. Thank you.

**Comment by sethvargo** [comment]
Hi @jendakol 

This is currently under active design review and we hope to have something more concrete shortly. /cc @jeremyfaller

**Comment by jendakol** [comment]
Oh. So the advice, for now, is to go through the whole process including VC verification, with this may be optimized in near future?

**Comment by sethvargo** [comment]
Hi @jendakol 

The _revisionToken_ is different than future key upload. The _revisionToken_ is for when symptoms change (not all states/countries support changing symptoms). Some areas allow self-reporting (e.g. "I feel sick"), which would trigger a key upload. Then, a few days later, the person goes to a doctor and tests positive. The _revisionToken_ revises (changes) the risk score of the previously-uploaded keys. This exists and is functional today, but it's a per-PHA configuration option.

The _nextKey-token_ is for future key upload. This scenario is for when someone tests positive, but then continues to interact with the world, collecting and broadcasting IDs. That device needs a way to upload keys for ~14 days beyond the original infection event. This is the bottom part of the diagram, and is not currently implemented.

**Comment by jendakol** [comment]
"Not implemented" explains a lot :smile:  

Let me explain my scenario - I need to publish many keys to the Key server, but it's configured to accept only 30 keys (default value) at once. So I need to split them by 30 and send them in batches. And obviously, even though I am able to get myself a new VC and verify it, I don't want to do it because it _seems unnecessary_ for me.  
But from what you say, it looks like I have no other option than to really do the whole this process again and again for each batch of 30 keys :-) And, as a side effect, not use the `revisionToken` at all since I won't ever change once uploaded keys.
Is that right?

**Comment by sethvargo** [comment]
30 keys feels like a lot - what is your RPI? /cc @mikehelmick

**Comment by mikehelmick** [comment]
In a production environment, one should never have more than 30 keys over a 14 day period, even that number is arrived at by maximizing all assumptions.

If in test scenarios you are having more keys, I recommend wiping the TEKs from the device every couple of days.

The token for further publishing is intended for uploading on successive days after the initial upload.

**Comment by jendakol** [comment]
I'm publishing those keys from out backend - I'm working on an integration of EFGS, so these keys are downloaded keys from other countries and there can easily be quite a lot of them.  
BTW we're having some EFGS related call with people from Google tomorrow, is that with you? :-)

**Comment by mikehelmick** [comment]
Using verification + the publish API is not the correct mechanism for EFGS integration.

Yes - I will be on the call tomorrow. Going to
/close
this issue for now.

**Comment by jendakol** [comment]
Well, it's definitely not the _ideal_ way how to it but we needed to do that from "outside", without modification of the Key server. But let's keep details for the call tomorrow.

And, BTW, thanks for your lightning reactions here :-)
