### ISSUE TITLE
user-issue statistics

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#799]
Currently there are statistics per realm and statistics per user (if you navigate to the user)

Request:
Show codes issued by user - possibly over time, possibly per day.

/kind enhancement

**Comment by sethvargo** [comment]
Across all realms or for a specific realm? How is this different from the existing user stats?

**Comment by mikehelmick** [comment]
Within a specific realm.

For example - if a realm issues 20 codes on a day, being able to identify which user's issued how many codes.

No specific codes that were issued.

**Comment by jeremyfaller** [comment]
#828 doesn't completely fix this issue. Mike has a few more requests. Specfically:

<quote>
In the table view of the stats - make the date clickable and then show who issued how many codes on that day
can you get that in, and then we can run it by the states that asked about this?
</quote>
