### ISSUE TITLE
Redirector App Store URLs for iOS don't allow post App Store triggering

### ISSUE THREAD

**Issue by flagxor** [google/exposure-notifications-verification-server#844]
Currently, redirector links don't allow an iOS app to use the trick described here:
https://firebase.google.com/docs/dynamic-links/operating-system-integrations

A landing page which contains JavaScript that stashes query parameters in the clipboard could be used to facilitate post-install continuation of a state specific app.
This might be desirable for a custom app using the verification server.

**Comment by sethvargo** [comment]
Talked with Brad offline, we'll

/close

this out for now.
