### ISSUE TITLE
Modify IAM permissions so that prevention of deletion is default

### ISSUE THREAD

**Issue by jeremyfaller** [google/exposure-notifications-verification-server#866]
Some discussion in the post-mortem 171305680 identified that we should modify our IAM permissions. @sethvargo doesn't think this is feasible.

**Comment by sethvargo** [comment]
Can confirm - I don't think this is feasible or a good ROI. I'd rather invest in making our scripts smarter.

**Comment by sethvargo** [comment]
We talked about this in the group sync today and decided not to do it. We're going to invest in better script intelligence instead.
