### ISSUE TITLE
Fire an alert when a project is being terminated

### ISSUE THREAD

**Issue by jeremyfaller** [google/exposure-notifications-verification-server#868]
In the post-mortem 171305680, we identified that we should be firing an alert when a project's being terminated.

**Comment by yegle** [comment]
This is a bit vague (what counts towards project termination?). Also, if we want alert for this event, and since the alert is part of a project, we are essentially trying to say "set up an alert and fire when alerts are deleted" :-(

Any thoughts?

**Comment by sethvargo** [comment]
I've thought about this more. None of the steps that occured in 171305680 would have actually deleted the project, so adding such an alert wouldn't have helped. I think it's safe to close this out as not-needed given our other remediation items.
