### ISSUE TITLE
[GCP] /api/verify unable to get signing key

### ISSUE THREAD

**Issue by zssz** [google/exposure-notifications-verification-server#89]
[Preamble] I succeeded in getting a long-term token by exchanging short-term token on a local dev environment:

```
zsombor@MacBook-Pro exposure-notifications-verification-server % go run ./cmd/get-token -code=55582912 -apikey=7F1rJF7XkZUvmUyOF8j5K3R7RYzOa6DqTYbQCov974dfitNW/52a+q/MJ95lGLaUZCli3+irRV7z5H3v0dw57g
2020/06/30 13:47:08 Sending: {VerificationCode:55582912}
2020/06/30 13:47:09 Result: 
{TestType:confirmed TestDate:2020-06-30 VerificationToken:eyJhbGciOiJFUzI1NiIsImtpZCI6InYxIiwidHlwIjoiSldUIn0.eyJhdWQiOiJkaWFnbm9zaXMtdmVyaWZpY2F0aW9uLWV4YW1wbGUiLCJleHAiOjE1OTM2MDA0MjgsImp0aSI6InV2ZmpWZk9xcHZOS253ZEtBQ05lN0pEeW4ybFdZWHdhRWoxdklZU2tEcUdYU2hLcm1jYjhuVWs2WUdaL25EL0FXU1hJQzl5S0ZZMktkU2hRclJQSWJRUGVLQzZSRWNSZlEwZ2Jod3A0ODNTTERocjdVUjJydG5xZWlxekRaeHNSIiwiaWF0IjoxNTkzNTE0MDI4LCJpc3MiOiJkaWFnbm9zaXMtdmVyaWZpY2F0aW9uLWV4YW1wbGUiLCJzdWIiOiJjb25maXJtZWQuMjAyMC0wNi0zMCJ9.UYBbtgc2wTmY23zo7fb2YKTfanU1l_9KKVNuLLonPStKXUQJCwB8_lO5MSIZlnXo2ye4kl-W2gnV9xVMU70kSA Error:}
zsombor@MacBook-Pro exposure-notifications-verification-server % go run ./cmd/get-token -code=55582912 -apikey=7F1rJF7XkZUvmUyOF8j5K3R7RYzOa6DqTYbQCov974dfitNW/52a+q/MJ95lGLaUZCli3+irRV7z5H3v0dw57g
2020/06/30 13:47:41 Sending: {VerificationCode:55582912}
2020/06/30 13:47:42 Result: 
{TestType: TestDate: VerificationToken: Error:verification code used}
```  

I am trying to do the same on a GCP-deployed server, but fail to do so.

Cloud Run logs:
`2020-06-30 15:22:19.926 EESTunable to get signing key: failed to fetch public key: rpc error: code = InvalidArgument desc = Resource name 'projects/REDACTED/locations/us-central1/keyRings/verification/cryptoKeys/token-signer' does not match pattern 'projects/([^/]+)/locations/([a-zA-Z0-9_-]{1,63})/keyRings/([a-zA-Z0-9_-]{1,63})/cryptoKeys/([a-zA-Z0-9_-]{1,63})/cryptoKeyVersions/([a-zA-Z0-9_-]{1,63})'.`

It looks like Terraform does not set the correct value for the env variable `TOKEN_SIGNING_KEY` (and `CERTIFICATE_SIGNING_KEY`)
https://github.com/google/exposure-notifications-verification-server/blob/969073d5e613cf6a2328a3f5371b1691d56d1ed0/terraform/services.tf#L44 /cc @sethvargo 

Modifying `TOKEN_SIGNING_KEY` (and `CERTIFICATE_SIGNING_KEY`) manually to end with `/cryptoKeyVersions/1`, and redeploying the services, resolves this particular issue.

However, the /api/verify call still fails, but with another error:
`2020-06-30 16:25:31.047 EESTunable to get signing key: failed to fetch public key: rpc error: code = PermissionDenied desc = Permission 'cloudkms.cryptoKeyVersions.viewPublicKey' denied on resource 'projects/REDACTED/locations/us-central1/keyRings/verification/cryptoKeys/token-signer/cryptoKeyVersions/1' (or it may not exist).`

**Comment by sethvargo** [comment]
Ah. We need to set the _version_, not the key. This is a bug. I'm OOO this week. A primitive fix is to append `/cryptoKeyVersions/1` to that URL. A more sophisticated fix would use a data source to lookup the version and its self link.

**Comment by zssz** [comment]
I modified the URL to point to `/cryptoKeyVersions/1`, but that doesn't make the problem go away (see PermissionDenied error in the Cloud Run log in the bottom of my previous message).

**Comment by sethvargo** [comment]
Can you check if the key exists in that region in your project?

**Comment by zssz** [comment]
It looks like they exist:
```
zsombor@MacBook-Pro exposure-notifications-verification-server % gcloud kms keys describe token-signer --keyring=verification --location=us-central1
createTime: '2020-06-30T11:36:26.535207024Z'
name: projects/REDACTED/locations/us-central1/keyRings/verification/cryptoKeys/token-signer
purpose: ASYMMETRIC_SIGN
versionTemplate:
  algorithm: EC_SIGN_P256_SHA256
  protectionLevel: HSM
zsombor@MacBook-Pro exposure-notifications-verification-server % gcloud kms keys describe certificate-signer --keyring=verification --location=us-central1
createTime: '2020-06-30T11:36:26.556647861Z'
name: projects/REDACTED/locations/us-central1/keyRings/verification/cryptoKeys/certificate-signer
purpose: ASYMMETRIC_SIGN
versionTemplate:
  algorithm: EC_SIGN_P256_SHA256
  protectionLevel: HSM
zsombor@MacBook-Pro exposure-notifications-verification-server % 
```

**Comment by mikehelmick** [comment]
/assign

working on a fix for this now.
