### ISSUE TITLE
Disable access on run.app urls

### ISSUE THREAD

**Issue by icco** [google/exposure-notifications-verification-server#895]
If you run on Google Cloud Run behind a GCLB, the run.app urls which are generated still exist. We should make an option that blocks requests that didn't come through an LB if we're behind a GCLB. It should default to off.

**Comment by yuriatgoogle** [comment]
This can be accomplished using the --ingress [flag](https://cloud.google.com/sdk/gcloud/reference/alpha/run/deploy#--ingress) in Cloud Run, targeted for general availability by January.

**Comment by sethvargo** [comment]
Do we know when it's targeted for beta? I know it's alpha now.

**Comment by yuriatgoogle** [comment]
Public preview "soon".


*Yuri Grinshteyn*

Customer Reliability Engineering

thegrinch@google.com

**Comment by yegle** [comment]
This is implemented by adding the following input variable in the config. The change was applied to our hosted key server and verification server. Consider this bug fixed.

```
  default_annotations_overrides = {
    "run.googleapis.com/ingress" : "internal-and-cloud-load-balancing"
  }
```

**Comment by sethvargo** [comment]
Thanks @yegle !
