### ISSUE TITLE
Switch to text/template for emails

### ISSUE THREAD

**Issue by sethvargo** [google/exposure-notifications-verification-server#901]
### TL;DR
`html/template` is escaping URLs. Marking them as safe still applies some escaping. 

**Expected behavior**
`template.URL` treats a URL like a URL. `template.HTML` does no escaping as documented.

**Observed behavior**
`template.URL` and `template.HTML` change the URL into an unusable format.

**Screenshots**
<img width="759" alt="screenshot-20201026-213059@2x" src="https://user-images.githubusercontent.com/408570/97247113-5d8e1e80-17d5-11eb-9a68-04646745e49c.png">

**Recommendation**
We should switch to text/template **only** for sending emails.

/assign @whaught

**Comment by sethvargo** [comment]
/cc @jeremyfaller 

If you have some cycles to put together a small repro, I think the Go team should know about this. At the very least, much of the docs on `html/template` seem to be inaccurate (e.g. `template.HTML` says "no escaping will be done", but escaping is definitely being done).

**Comment by jeremyfaller** [comment]
Dunno if this is a doc, or code problem. If code, it might be a relatively serious regression. I'll take a look ASAP as the code freeze is coming.

**Comment by whaught** [comment]
/close

This is done. The escaping issue was actually the content-type header of the email (golang unescape does work)
