### ISSUE TITLE
Add API Keys to cleanup job

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#905]
### TL;DR

Our e2e test runner has created hundreds of API keys

API Keys should be deleted ~30 days after they have been disabled.

We may want to also consider a metric for only keeping the most recent X API keys of each type (50?)

These are outsized things that should only occur in tests

/kind enhancement

**Comment by sethvargo** [comment]
30 days feels like a long time. You would know pretty quickly if you deleted an API key that was still in use. https://github.com/google/exposure-notifications-verification-server/pull/909 uses a week.

**Comment by sethvargo** [comment]
I personally don't think we need an alert or limit on the number of API keys.

**Comment by mikehelmick** [comment]
My reasoning for 30d - an API key may be already embedded in a live application and if accidentally disabled, I wanted to give longer time for re-activating before the app has an unrecoverable outage.

**Comment by sethvargo** [comment]
Sure, but do you think it would take 30 days to make that determination? That feels like a really long time to not be aware of an outage.

It's not a hill upon which I plan to die. We can make it 30 days, but that feels too long to me.

**Comment by mikehelmick** [comment]
Talked on chat, we'll make the default 14d
