### ISSUE TITLE
Build tag missing from some metrics

### ISSUE THREAD

**Issue by icco** [google/exposure-notifications-verification-server#906]
### TL;DR
All metrics should have a label with the build version, it seems to have disappeared in some cases. Let's find out why.

**Expected behavior**

A label for build_id and build_version on all metrics.

**Observed behavior**

Both labels were missing in the /rate_limited.* metrics

**Comment by sethvargo** [comment]
I think this might have happened during the metrics refactor @yegle was working on?

**Comment by yegle** [comment]
#907 should also fix this issue.
