### ISSUE TITLE
System admin - view mobile apps

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#910]
### TL;DR

For coordinating EN Express (ENX) and understanding what should be happening with the ENX redirect service:

* Surface configured mobile apps to system admins

/kind enhancement

**Comment by sethvargo** [comment]
Broken down by realm or just a total list?

**Comment by mikehelmick** [comment]
Both views would be awesome

1) when viewing an individual realm, show this

2) view a list of all mobile apps configured in the system
