### ISSUE TITLE
Container seem to exit ~immediately when SIGTERM is received

### ISSUE THREAD

**Issue by yegle** [google/exposure-notifications-verification-server#912]
I've noticed we have several "failed to export metric" log lines, usually associate with server shutdown.

![image](https://user-images.githubusercontent.com/146133/97345089-e2fde700-1846-11eb-80d8-e3f63a07089c.png)

Per the Cloud Run container contract (https://cloud.google.com/run/docs/reference/container-contract#instance-shutdown) when killing a container a `SIGTERM` is sent first, and `SIGKILL` 10s later.

A 10s window should be sufficient to flush the remaining timeseries that has not be uploaded yet. Per the following query our 99pct latency of `CreateTimeSeries` call rarely exceeds 10s:

```
fetch generic_task
| metric 'custom.googleapis.com/opencensus/grpc.io/client/roundtrip_latency'
| filter
    (metric.grpc_client_method
     == 'google.monitoring.v3.MetricService/CreateTimeSeries')
| align delta(1m)
| every 1m
| group_by [],
    [value_roundtrip_latency_percentile:
       percentile(value.roundtrip_latency, 99)]
```

![image](https://user-images.githubusercontent.com/146133/97345606-7c2cfd80-1847-11eb-8125-216e4114b058.png)

Did we make some mistake in our signal handling code that result in this issue?

**Comment by sethvargo** [comment]
We use https://github.com/sethvargo/go-signalcontext which cancels the propagated context throughout when getting `SIGTERM` or `SIGINT`. My guess is that the context given to the metrics exporter is also being closed?

**Comment by yegle** [comment]
It's using a shared context here: https://github.com/google/exposure-notifications-server/blob/1fbede9cb885d0e4f4d88f836f8ed08311c6fa3d/pkg/observability/stackdriver.go#L49

So what should happen is:
1. Have a separate ctx for metric exporting, so that it won't be canceled by the signal context library.
2. Upon receiving `SIGTERM`, cancel other contexts, call `observability.Exporter.Close()` in a different go routine.
3. Leave the go routine running until either the RPC finishes or the process receives `SIGKILL`.

I don't fully understand how the signal context library works. Seth, do you think the steps above makes sense?

**Comment by sethvargo** [comment]
@yegle the signal context library is very small. It creates a cancellable context:

```go
ctx, cancel := context.WithCancel(context.Background())
```

And then calls `cancel()` when the signal is received. It's also [in the standard library now](https://github.com/golang/go/commit/b6dbaef68fdbb3f14387e4c32a8890144220f54e) but hasn't yet been released.

I think:

1. Create a new `metricsCtx` for the metrics exporter.

2. Trap parent context's cancellation:

    ```go
    <-ctx.Done()
    ```

3. Close observability exporter

4. Wait for stop in the main routine (this will require the observability exporter to return a context or channel upon which to listen)
