### ISSUE TITLE
Add observability and audit logging when burst capacity is added.

### ISSUE THREAD

**Issue by yuriatgoogle** [google/exposure-notifications-verification-server#926]
### TL;DR
Add a log entry when adding burst capacity through the admin UI.

**Comment by mikehelmick** [comment]
audit log entry?

**Comment by sethvargo** [comment]
We should probably have an audit log entry too, but this looks specific about observability.

**Comment by yuriatgoogle** [comment]
Should be both, I suppose.


*Yuri Grinshteyn*

Customer Reliability Engineering

thegrinch@google.com
