### ISSUE TITLE
Use super trim

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-verification-server#933]
Move the trim function from
  https://github.com/google/exposure-notifications-verification-server/pull/931

Into a common location 

use this instead of the standard strings.TrimSpace

/kind enhancement

**Comment by sethvargo** [comment]
We may want to consider inverting the logic to an _allowed_ list of characters. There are many non-printable unicode characters and other printable unicode characters that we wouldn't want to allow. 👍 is valid unicode, but it's not valid in a certificate.
